BootStrap: library
From: cokelaer/damona/sequana:0.9.1

%labels
    AUTHOR thomas cokelaer
    VERSION v1.0.0

%post

    # set anaconda path
    export PATH=$PATH:/usr/local/anaconda/bin

    conda install fastqc==0.11.9
    conda install falco
    pip install sequana_fastqc==1.1.0 --no-deps
    pip install sequana_pipetools  --no-deps
    conda clean --packages -y
    conda clean --all -y # next requires lots of space

    if [ ! -d /data ]; then mkdir /data; fi

    echo "backend:agg" > matplotlibrc


%environment
    export PATH=$PATH:/usr/local/anaconda/bin
    export LANG=C   # prevents perl for raising warnings
    export PERL5LIB=/usr/local/anaconda/lib/perl5/5.22.0
    export LANG=C.UTF-8
    export LC_ALL=C.UTF-8

%runscript
    exec sequana_fastqc "$@"

