Bootstrap: docker
From: ubuntu:20.04

%labels
   MAINTAINER Arun Seetharam
   EMAIL arnstrm@iastate.edu

%test
    python3 --version

%environment
#   export PATH=$PATH:/opt/egnep-1.6.5/bin/ext/bin
#   export PERl5LIB=$PERl5LIB:/opt/egnep-1.6.5/bin/ext/bin
#   export MANPATH=$MANPATH:/opt/egnep-1.6.5/bin/ext/man
#   export PATH=$PATH:/opt/egnep-1.6.5/bin/ext/Red-2.0/bin
   

%post

    apt update
    apt install -y software-properties-common
    add-apt-repository universe
    add-apt-repository multiverse
    add-apt-repository restricted
    DEBIAN_FRONTEND=noninteractive
    echo "deb http://dk.archive.ubuntu.com/ubuntu/ xenial main" >> /etc/apt/sources.list
    echo "deb http://dk.archive.ubuntu.com/ubuntu/ xenial universe" >> /etc/apt/sources.list
    add-apt-repository ppa:linuxuprising/libpng12
    apt update
    apt update
    apt install -y build-essential wget curl git autoconf automake
    apt install -y g++-5 gcc-5 bison make cmake
    apt install -y perl zlib1g-dev libbz2-dev liblzma-dev libcurl4-gnutls-dev libssl-dev libncurses5-dev liblpsolve55-dev rsync librsync-dev libgd-dev libtool
    apt install -y libboost-dev '^libboost-.*71-dev'
    apt install -y perl
    apt install -y python3 python3-numpy python3-dev python3-scipy python3-pandas python3-pip libtool liblzma-dev
    apt install -y libcurl4-gnutls-dev zlib1g-dev
    apt install libpng12-0
    pip install cython numpy scipy
    pip install RGT --no-binary RGT
