Bootstrap: docker

from: python:2.7.11

%post
    pip install  'cython==0.23.4'
    pip install  'pysam>=0.9.0,<0.9.2'
    pip install  'numpy==1.10.0'

    #(Optional)
    pip install  'bx-python==0.7.3'
    pip install  'mygene==3.0.0'

    #(Now FusorSV package)
    pip install https://github.com/timothyjamesbecker/FusorSV/releases/download/0.1.2-beta/fusorsv-0.1.2.tar.gz
