#!/bin/bash
#
# Emilie Ait Yahya <emilie.aityahya@chru-lille.fr>
# 2018/11/06: initial version


BootStrap: docker
From: phusion/baseimage:0.11

%labels
  MAINTAINER emiile.aityahya@chru-lille.fr

%environment
  export  LC_ALL=en_US.UTF-8
  export  LANGUAGE=en_US.UTF-8
  export  PATH="/miniconda/bin/:${PATH}"
%help


%post
	echo 'debconf debconf/frontend select Noninteractive' | debconf-set-selections

  apt-get update
  apt-get -y install build-essential \
  wget 


  wget https://repo.continuum.io/miniconda/Miniconda2-4.7.12.1-Linux-x86_64.sh 

  bash Miniconda2-4.7.12.1-Linux-x86_64.sh -p /miniconda -b
  rm   Miniconda2-4.7.12.1-Linux-x86_64.sh
  export  PATH="/miniconda/bin/:${PATH}"

  conda config --add channels defaults
  conda config --add channels bioconda
  conda config --add channels conda-forge
  conda config --set ssl_verify no
  conda config --set default_threads 12


  ## install svtools
  conda install -c bioconda svtools=0.4.0