Bootstrap: docker
From: conda/miniconda3
Stage: devel

%files
environment.yml /environment.yml

 
%post

apt-get update && apt-get install -y  procps 
conda update -n base -c defaults conda
conda env create -n environment -f /environment.yml
conda install -c conda-forge conda-pack
conda-pack -n environment -o /tmp/env.tar && mkdir /venv && cd /venv && tar xf /tmp/env.tar && rm /tmp/env.tar
/venv/bin/conda-unpack
chmod +x /venv/bin/*



Bootstrap: docker
From: debian:buster-slim 
Stage: final
IncludeCmd: yes

%files from devel
/venv /venv

%files
debian.packages.run.list /opt/packages.run.list
SOFTWARE.tsv /opt

%post
apt update && apt install -y $(cat /opt/packages.run.list)
apt clean

mkdir -p /opt/wrappers
echo "#!/bin/bash\ncat /opt/SOFTWARE.tsv\n" > /opt/wrappers/software_info
chmod +x /opt/wrappers/software_info

%environment
export PATH=/venv/bin:/opt/wrappers:$PATH

%runscript
"$@"

%test

%labels
    Maintainer Sebastien.Carrere@inrae.fr
    Version 0.1.16

%help
## VCFTOOLS

VcfTools: A set of tools written in Perl and C++ for working with VCF files

### USAGE

	$ {IMAGE} vcftools

### CITATION

The Variant Call Format and VCFtools, Petr Danecek, Adam Auton, Goncalo Abecasis, Cornelis A. Albers, Eric Banks, Mark A. DePristo, Robert Handsaker, Gerton Lunter, Gabor Marth, Stephen T. Sherry, Gilean McVean, Richard Durbin and 1000 Genomes Project Analysis Group, Bioinformatics, 2011
