Bootstrap: docker
From: alpine:edge

%labels
    AUTHOR icaoberg
    MAINTAINER icaoberg@psc.edu
    WEBSITE https://github.com/icaoberg/singularity-hyperfine
    VERSION 1.11.0

%post
    apk update
    apk add hyperfine

####################################################################################
