Bootstrap: docker
From: quay.io/biocontainers/sra-tools:2.10.8--pl526haddd2b5_0

%labels
    MAINTAINER icaoberg
    EMAIL icaoberg@psc.edu
    SUPPORT help@psc.edu
    REPOSITORY http://github.com/pscedu/singularity-sra-toolkit
    COPYRIGHT Copyright © 2021 Pittsburgh Supercomputing Center. All Rights Reserved. 
    VERSION 2.10.8