Bootstrap: docker
From: alpine

%labels
    AUTHOR icaoberg
    MAINTAINER icaoberg@psc.edu
    WEBSITE https://github.com/icaoberg/singularity-bat
    VERSION 0.17.1

%post
    apk update
    apk add bat
