Bootstrap: docker
From: ubuntu:16.04

# sudo singularity build greeting.sif Singularity

%post

    # Write an echo statement to the second and third line of the shell action
    cat > /.singularity.d/env/99-motd.sh <<EOF
case \$0 in
    /.singularity.d/actions/shell)
        echo "Hello \$USER!"
        echo ;;
esac
EOF
