Bootstrap: docker
From: ubuntu:xenial

%setup
     ## The "%setup"-part of this script is called to bootstrap an empty
     ## container. It copies the source files from the branch of your
     ## repository where this file is located into the container to the
     ## directory "/planner". Do not change this part unless you know
     ## what you are doing and you are certain that you have to do so.

    REPO_ROOT=`dirname $SINGULARITY_BUILDDEF`
    cp -r $REPO_ROOT/ $SINGULARITY_ROOTFS/planner

%post

    ## The "%post"-part of this script is called after the container has
    ## been created with the "%setup"-part above and runs "inside the
    ## container". Most importantly, it is used to install dependencies
    ## and build the planner. Add all commands that have to be executed
    ## once before the planner runs in this part of the script.

    ## Install all necessary dependencies.
    apt-get update
    apt-get -y install g++ make python

    ## Build your planner
    cd /planner/src
    ./build_all -j4

    ## Strip binaries.
    strip --strip-all /planner/src/preprocess/preprocess
    strip --strip-all /planner/src/search/downward-release

    ## Remove packages unneeded for running the planner.
    apt -y autoremove cmake g++ make autotools-dev automake gcc g++-multilib
    rm -rf /var/lib/apt/lists/*

    ## Only keep essential binaries.
    mkdir -p /compiled-planner/src/preprocess
    mkdir -p /compiled-planner/src/search
    mv /planner/src/driver /planner/src/fast-downward.py /compiled-planner/src
    mv /planner/src/preprocess/preprocess /compiled-planner/src/preprocess
    mv /planner/src/translate /compiled-planner/src/translate
    mv /planner/src/search/downward-release /compiled-planner/src/search
    rm -rf /planner
    mv /compiled-planner /planner

%runscript
    ## The runscript is called whenever the container is used to solve
    ## an instance.

    DOMAINFILE=$1
    PROBLEMFILE=$2
    PLANFILE=$3

    ## Call your planner.
    /planner/src/fast-downward.py \
        --plan-file $PLANFILE \
        --portfolio /planner/src/driver/portfolios/seq_agl_ds.py \
        $DOMAINFILE \
        $PROBLEMFILE \
        --preprocess-options --h2-time-limit 10

## Update the following fields with meta data about your submission.
## Please use the same field names and use only one line for each value.
%labels
Name        DecStar
Description portfolio including decoupled search as a main component
Authors     Daniel Gnad <gnad@cs.uni-saarland.de> and Alexander Shleyfman <shleyfman.alexander@gmail.com> and Joerg Hoffmann <hoffmann@cs.uni-saarland.de>
SupportsDerivedPredicates no
SupportsQuantifiedPreconditions no
SupportsQuantifiedEffects yes
