BootStrap: docker
From: alpine:latest

%labels
  Maintainer Christian Dietrich
  STAR_Version 2.7.0f

%apprun STAR
  exec STAR "${@}"
  
%apprun STARlong
  exec STARlong "${@}"

%runscript
  exec STAR "${@}"

%post
  # Get dependencies
  apk update
  apk add gcc make g++ zlib zlib-dev libgomp libstdc++ libgcc

  # Install STAR
  cd /tmp
  wget https://github.com/alexdobin/STAR/archive/2.7.0f.tar.gz
  tar zxf 2.7.0f.tar.gz
  cd STAR-*/source
  sed -i '14i #include "sys/types.h"' SharedMemory.h
  make -j$(nproc) STAR STARlong
  cp STAR STARlong /usr/local/bin/

  # Clean up
  apk del gcc make g++ zlib-dev
  rm -rf /var/cache/apk/*
  rm -rf /tmp/*
