Bootstrap: docker
From: nvidia/cuda:9.0-cudnn7-runtime-ubuntu16.04


%environment

  PATH=/opt/conda/envs/cryolo/bin:/opt/conda/bin:/usr/local/nvidia/bin:/usr/local/cuda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

%post

  export LANG=C.UTF-8 LC_ALL=C.UTF-8
  export PATH=/opt/conda/bin:$PATH

  apt-get update -y
  apt-get update --fix-missing && apt-get install -y wget bzip2 ca-certificates build-essential \
    libgtk2.0-0 libxxf86vm1 

  wget --quiet https://repo.anaconda.com/miniconda/Miniconda2-latest-Linux-x86_64.sh -O /tmp/miniconda.sh && \
      /bin/bash /tmp//miniconda.sh -b -p /opt/conda && \
      rm /tmp/miniconda.sh && \
      ln -s /opt/conda/etc/profile.d/conda.sh /etc/profile.d/conda.sh && \
      echo ". /opt/conda/etc/profile.d/conda.sh" >> ~/.bashrc && \
      echo "conda activate base" >> ~/.bashrc

  # deps
  /opt/conda/bin/conda create -n cryolo -c anaconda python=3.6 pyqt=5 cudnn=7.1.2 numpy==1.14.5 cython wxPython==4.0.4 intel-openmp==2019.4
  # /opt/conda/bin/conda init bash
  #. /opt/conda/bin/activate cryolo

  /opt/conda/envs/cryolo/bin/pip install 'cryolo[gpu]'

  echo "export LD_LIBRARY_PATH=/opt/conda/envs/cryolo/lib:$LD_LIBRARY_PATH"  >>$SINGULARITY_ENVIRONMENT
  echo "export SINGULARITYENV_PREPEND_PATH=/opt/conda/envs/cryolo/bin"  >>$SINGULARITY_ENVIRONMENT
