Bootstrap: docker
From: python:latest

%labels
    MAINTAINER icaoberg
    EMAIL icaoberg@psc.edu
    SUPPORT help@psc.edu
    REPOSITORY https://github.com/pscedu/singularity-checkm
    COPYRIGHT Copyright © 2021 Pittsburgh Supercomputing Center. All Rights Reserved.
    VERSION 1.1.3

%post
    apt update
    apt install -y git gcc zlib1g zlib1g-dev wget bzip2 build-essential libz-dev
    cd /opt
    wget -nc https://github.com/samtools/htslib/releases/download/1.9/htslib-1.9.tar.bz2
    tar -vxjf htslib-1.9.tar.bz2 && rm -fv htslib-1.9.tar.bz2
    cd htslib-1.9
    make
    make install
    pip3 install numpy scipy matplotlib pysam dendropy cython checkm-genome
