Bootstrap: docker
From: quay.io/biocontainers/star:2.7.6a--0

%labels
    MAINTAINER icaoberg
    EMAIL icaoberg@psc.edu
    REPOSITORY https://github.com/pscedu/singularity-star
    COPYRIGHT Copyright © 2021 Pittsburgh Supercomputing Center. All Rights Reserved.
    VERSION 2.7.6a
