Bootstrap: docker
From: quay.io/biocontainers/star:2.7.6a--0

%labels
    AUTHOR icaoberg
    EMAIL icaoberg@psc.edu
    WEBSITE http://www.andrew.cmu.edu/~icaoberg
    VERSION 2.7.6a

%post
   rm /etc/resolv.conf

####################################################################################
