BootStrap: docker
From: continuumio/miniconda3:4.10.3

%post
  VER=3.1.6-1 && \
  VER_SHORT=${VER%-*}  && \
  apt update && \
  apt install -y \
    curl && \
  rm -rf /var/lib/apt/lists/* && \
  cd /tmp && curl -LO https://github.com/harelba/q/releases/download/v${VER_SHORT}/q-text-as-data-${VER}.x86_64.deb && \
  dpkg -i q-text-as-data-${VER}.x86_64.deb && \
  rm -f /tmp/q-text-as-data-${VER}.x86_64.deb
