Bootstrap: docker
From: debian:stretch-slim

%setup
    # install your pipeline script into /usr/local/bin
    install -m 755 ./code/* ${SINGULARITY_ROOTFS}/usr/local/bin

%environment
    export LC_ALL=C

%post
    apt-get update && apt-get -y -V upgrade
    apt-get -y install curl gnupg apt-transport-https wget

    # NeuroDebian
    curl http://neuro.debian.net/lists/stretch.de-md.full -o /etc/apt/sources.list.d/neurodebian.sources.list
    apt-key adv --recv-keys --keyserver hkp://pool.sks-keyservers.net:80 0xA5D32F012649A5A9
    apt-get update

    # ANTs
    apt-get -y install ants

    # FSL
    apt-get -y install fsl-core fsl-atlases

    # AFNI
    apt-get -y install afni

    # Workbench
    apt-get -y install connectome-workbench

    # cleanup
    apt-get autoremove
    apt-get autoclean

%runscript
    eval "export LC_ALL=C"
    eval "export ANTSPATH=/usr/lib/ants"
    eval "export PATH=${PATH}:/usr/lib/ants"
    eval "source /etc/fsl/fsl.sh"
    eval "source /etc/afni/afni.sh"

%labels
    Author Kyesam Jung (k.jung@fz-juelich.de)
    Version 0.0.1

%help
    This pipeline is based on a proof-of-concept container for VBC pipelines (Alex Waite, v0.4.0).
    This container allows you to run the most wonderful shell command ever created.
