Bootstrap: docker
From: alpine:edge
Includecmd: no

%labels
    MAINTAINER icaoberg
    EMAIL icaoberg@psc.edu
    SUPPORT help@psc.edu
    REPOSITORY  https://gitlab.psc.edu/icaoberg/singularity-ffmpeg
    COPYRIGHT Copyright © 2022-2023 Pittsburgh Supercomputing Center. All Rights Reserved. 
    VERSION 6.0-r26

%post
    apk add --update ffmpeg

%runscript
    ffmpeg "$@"
