Bootstrap: docker
From: continuumio/anaconda3

%labels
    AUTHOR icaoberg
    EMAIL icaoberg@psc.edu
    SUPPORT help@psc.edu
    REPOSITORY http://gitub.com/pscedu/singularity-bsmap
    COPYRIGHT Copyright © 2021 Pittsburgh Supercomputing Center. All Rights Reserved.
    VERSION 2.90

%post
    apt update
    conda install -c conda-forge -c bioconda bsmap
