Bootstrap: docker
From: ubuntu:20.04

%labels
    MAINTAINER icaoberg
    EMAIL icaoberg@psc.edu
    SUPPORT help@psc.edu
    REPOSITORY http://github.com/pscedu/singularity-spades
    COPYRIGHT Copyright © 2022 Pittsburgh Supercomputing Center. All Rights Reserved. 
    VERSION 3.15.5

%environment
    export PATH=$PATH:/opt/SPAdes-3.15.5-Linux/bin

%post
    apt update
    apt install -y wget g++ cmake zlib1g bzip2 python3 python
    cd /opt/
    wget -nc https://github.com/ablab/spades/releases/download/v3.15.5/SPAdes-3.15.5-Linux.tar.gz
    tar -xzf SPAdes-3.15.5-Linux.tar.gz
    rm -fv SPAdes-3.15.5-Linux.tar.gz
