Bootstrap: docker
From: staphb/prokka:1.14.5

%labels
    AUTHOR icaoberg
    EMAIL icaoberg@psc.edu
    WEBSITE http://gitlab.psc.edu/icaoberg/singularity-prokka
    VERSION 1.14.5

%post
#   rm /etc/resolv.conf

####################################################################################
