Bootstrap: docker
From: nvidia/cuda:9.0-runtime-ubuntu16.04


%environment

  PATH=/opt/conda/bin:/usr/local/nvidia/bin:/usr/local/cuda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

%post

  export LANG=C.UTF-8 LC_ALL=C.UTF-8
  export PATH=/opt/conda/bin:$PATH


  apt-get update --fix-missing && apt-get install -y wget bzip2 ca-certificates \
      libglib2.0-0 libxext6 libsm6 libxrender1 \
      git mercurial subversion

  wget --quiet https://repo.anaconda.com/miniconda/Miniconda2-4.4.10-Linux-x86_64.sh -O ~/miniconda.sh && \
      /bin/bash ~/miniconda.sh -b -p /opt/conda && \
      rm ~/miniconda.sh && \
      ln -s /opt/conda/etc/profile.d/conda.sh /etc/profile.d/conda.sh && \
      echo ". /opt/conda/etc/profile.d/conda.sh" >> ~/.bashrc && \
      echo "conda activate base" >> ~/.bashrc

  # deps
  /opt/conda/bin/conda install -y "conda>=4.5.2" -c defaults
  /opt/conda/bin/conda install -y cmake=3.9 -c defaults

  apt-get update -y

  apt-get install -y libgl1-mesa-dev libglu1-mesa-dev pkg-config xfonts-base xfonts-100dpi xfonts-75dpi xfonts-cyrillic
  /opt/conda/bin/conda install eman-deps=13.2 -c cryoem -c defaults -c conda-forge -y
  /opt/conda/bin/conda install future 

  mkdir -p /opt/eman2/src
  git clone https://github.com/cryoem/eman2.git /opt/eman2/src

  mkdir -p /opt/eman2/build && cd /opt/eman2/build
  apt-get install -y build-essential
  apt-get install -y make g++
  /opt/conda/bin/cmake ../src \
    -DENABLE_CONDA=ON \
    -DENABLE_OPTIMIZE_MACHINE=ON \
    -DCONDA_PREFIX=/opt/conda \

  make -j

  echo "export LD_LIBRARY_PATH=/opt/conda/lib/:$LD_LIBRARY_PATH"  >>$SINGULARITY_ENVIRONMENT
  echo "export SINGULARITYENV_PREPEND_PATH=/opt/conda/bin"  >>$SINGULARITY_ENVIRONMENT

  make install

  # tests
  # export LD_LIBRARY_PATH=/opt/conda/lib/:$LD_LIBRARY_PATH
  # make test
