Bootstrap:docker
From:nfcore/base

%labels
	MAINTAINER Björn Hallström <bjorn.hallstrom@skane.se>
	DESCRIPTION Singularity container for CMD myeloid twist pipeline
	VERSION 0.0.3

%environment
	PATH=/opt/conda/envs/CMD-twist/bin:/opt/sentieon-genomics-201911/bin/:$PATH
	PICARD_HOME=/opt/conda/envs/CMD-twist/share/picard-2.18.26-0/
	PERL5LIB=$PERL5LIB:/opt/conda/envs/CMD-twist/lib/site_perl/5.26.2/
	export JAVA_HOME=/opt/conda/envs/CMD-twist
%files
        environment.yml /
        environment_samtools.yml /
	environment_py3.yml /
        /data/bnf/scripts/postaln_qc.pl /usr/local/bin
	/data/bnf/sw/sentieon/sentieon-genomics-201911 /opt
%post
        rm -rf /var/lib/apt/lists/*
        apt -y clean
        apt -y update
	apt -y install build-essential make

	/opt/conda/bin/conda env create -f /environment.yml
	/opt/conda/bin/conda env create -f /environment_samtools.yml
	/opt/conda/bin/conda env create -f /environment_py3.yml python=3
	/opt/conda/bin/conda clean -a
	
	/opt/conda/envs/CMD-twist/bin/cpanm JSON

	git clone https://github.com/Clinical-Genomics-Lund/qc_sentieon.git
	cd qc_sentieon
	git checkout c453713628a52125e72f5cadb7a0d1a44b058132
	cp qc_sentieon.pl /opt/conda/bin/.
		
