Bootstrap: docker
From: alpine

%labels
    MMAINTAINER icaoberg
    EMAIL icaoberg@psc.edu
    SUPPORT help@psc.edu
    REPOSITORY http://github.com/pscedu/singularity-graphviz
    COPYRIGHT Copyright © 2021 Pittsburgh Supercomputing Center. All Rights Reserved. 
    VERSION 2.44.0
%post
    apk update
    apk add graphviz

####################################################################################
