Bootstrap: docker
From: alpine

%labels
    AUTHOR icaoberg
    MAINTAINER icaoberg@psc.edu
    SUPPORT help@psc.edu
    REPOSITORY https://graphviz.org/
    VERSION 2.44.0

%post
    apk update
    apk add graphviz

####################################################################################
