Bootstrap: docker
From: quay.io/biocontainers/gatk4:4.1.9.0--py39_0

%labels
    AUTHOR icaoberg
    EMAIL icaoberg@psc.edu
    WEBSITE http://www.andrew.cmu.edu/~icaoberg
    VERSION 4.1.9.0

%post
   rm /etc/resolv.conf

####################################################################################
