Bootstrap: docker
From: quay.io/biocontainers/spades:3.15.3--h95f258a_0

%labels
    MAINTAINER icaoberg
    EMAIL icaoberg@psc.edu
    SUPPORT help@psc.edu
    REPOSITORY http://github.com/pscedu/singularity-spades
    COPYRIGHT Copyright © 2021 Pittsburgh Supercomputing Center. All Rights Reserved. 
    VERSION 3.15.3
