Bootstrap: docker
From: quay.io/biocontainers/bowtie2:2.4.2--py38h1c8e9b9_0

%labels
    MAINTAINER icaoberg
    EMAIL icaoberg@psc.edu
    WEBSITE https://github.com/pscedu/singularity-bowtie2
    COPYRIGHT Copyright © 2021 Pittsburgh Supercomputing Center. All Rights Reserved. 
    VERSION 2.4.2
