Bootstrap:docker
From:nfcore/base:1.8

%labels
	MAINTAINER Björn Hallström <bjorn.hallstrom@skane.se>
	DESCRIPTION Singularity container for CMD myeloid twist pipeline
	VERSION 0.0.4

%environment
	PATH=/opt/conda/envs/main-env/bin:/opt/sentieon-genomics-202010.01/bin/:$PATH
	PICARD_HOME=/opt/conda/envs/main-env/share/picard-2.25.2-0/
	PERL5LIB=$PERL5LIB:/opt/conda/envs/main-env/lib/site_perl/5.26.2/
	export JAVA_HOME=/opt/conda/envs/main-env
	umask 0002
%files
	environment.yml /
	
%post
	mkdir /usr/share/man/man1/
	rm -rf /var/lib/apt/lists/*
	apt -y clean
	apt -y update
	apt -y install build-essential make
	apt -y install graphicsmagick-imagemagick-compat libtbb2

	/opt/conda/bin/conda install mamba -n base -c conda-forge

	/opt/conda/bin/mamba env create -n main-env --file /environment.yml	

