Bootstrap: docker
From: scientificlinux/sl:7
#Bootstrap: localimage
#From: ../build/jacs_base-1.0.img

%help
Recipe for a Singularity container running Yang Yu's older aligners which require a legacy version of Vaa3d

%labels
NAME aligner_yuy_legacy
AUTHOR Konrad Rokicki
VERSION 1.0

%files
./aligner /opt/aligner

%post
cd /opt # Install all software in /opt

echo "Installing dependencies"
yum install -y ImageMagick bc perl
EPEL_FILE=epel-release-latest-7.noarch.rpm
curl -sL http://dl.fedoraproject.org/pub/epel/{$EPEL_FILE} -o '#1'
rpm -ivh $EPEL_FILE && /bin/rm -f $EPEL_FILE
yum install -y python-pip jq
pip install PyYAML==5.4.1 yq==2.12.2

echo "Installing Legacy Vaa3d"
# Prereqs for Vaa3d
yum install -y mesa-libGLU qt qt-x11 libXv numactl-libs
# Install Vaa3d
VAA3D_FILE=vaa3d-redhat-legacy.tgz
curl -sL https://github.com/JaneliaSciComp/tools-archive/releases/download/1.0.0/{$VAA3D_FILE} -o '#1'
tar xvf $VAA3D_FILE && /bin/rm -f $VAA3D_FILE
ln -s /opt/vaa3d_JaneliaWorkstation_4.0.0-sl72 Vaa3D
# Install linked libavcodec libraries under /groups
pushd /
VAA3DLIB_FILE=schauderd-libavcodec.tgz
curl -sL https://github.com/JaneliaSciComp/tools-archive/releases/download/1.0.0/{$VAA3DLIB_FILE} -o '#1'
tar xvf $VAA3DLIB_FILE && /bin/rm -f $VAA3DLIB_FILE
popd

echo "Installing ANTS"
ANTS_FILE=ants-yuy2013.tgz
curl -sL https://github.com/JaneliaSciComp/tools-archive/releases/download/1.0.0/{$ANTS_FILE} -o '#1'
tar xvf $ANTS_FILE && /bin/rm -f $ANTS_FILE

echo "Fixing permissions"
chown -R root:root /opt/*
chmod -R g+r /opt/*

%apprun brainalign40x_512px_INT
/opt/aligner/brainalign40x_512px_INT.sh "$@"
%apphelp brainalign40x_512px_INT
T. Lee Lab whole brain 40x aligner

%apprun whole_brain 
/opt/aligner/run_63x_aligner.sh "$@"
%apphelp whole_brain
Nern whole brain 63x unpaired aligner

%apprun central_brain
/opt/aligner/run_central_aligner.sh "$@"
%apphelp central_brain
Nern central brain 63x aligner. This currently doesn't work because we're missing lobe_seger.

