#!/bin/bash
#
# Christophe DEMAY <christophe.demay@chru-lille.fr>
# 2019/04/10: initial version


Bootstrap: docker
From: phusion/baseimage:0.11

%labels
  MAINTAINER christophe.demay@chru-lille.fr
  VERSION 4.4

%environment
  
%help

%post
	echo 'debconf debconf/frontend select Noninteractive' | debconf-set-selections
  apt-get clean 

    apt-get -y update
	apt-get -y install build-essential hashdeep