BootStrap: docker
From: alpine:latest

%labels
  Maintainer Christian Dietrich
  OpenJDK_Version 8.181.13

%apprun java
  exec java "${@}"
  
%runscript
  exec java "${@}"

%post
  # Install OpenJDK 8
  echo "http://mirror.leaseweb.com/alpine/v3.8/community" >> /etc/apk/repositories
  apk update
  apk add openjdk8
  
  # Clean up
  rm -rf /var/cache/apk/*
  rm -rf /tmp/*
