Bootstrap: docker
From: quay.io/biocontainers/bowtie2:2.2.5--py39h7cff6ad_8

%labels
    AUTHOR icaoberg
    EMAIL icaoberg@psc.edu
    WEBSITE https://github.com/pscedu/singularity-bowtie2
    COPYRIGHT Copyright © 2021 Pittsburgh Supercomputing Center. All Rights Reserved. 
    VERSION 2.2.5
