Bootstrap:docker
From:nfcore/base:1.8

%labels
	MAINTAINER Björn Hallström <bjorn.hallstrom@skane.se>
	DESCRIPTION Singularity container for CMD myeloid twist pipeline
	VERSION 0.0.4

%environment
	PATH=/opt/conda/envs/main-env/bin:/opt/sentieon-genomics-202010.01/bin/:$PATH
	PICARD_HOME=/opt/conda/envs/main-env/share/picard-2.25.2-0/
	PERL5LIB=$PERL5LIB:/opt/conda/envs/main-env/lib/site_perl/5.26.2/
	export JAVA_HOME=/opt/conda/envs/main-env
	umask 0002
%files
	environment.yml /
	environment_py2.yml /
	environment_java8.yml /
	environment_sambamba.yml /
	environment_old-cnvkit.yml

	/data/bnf/scripts/postaln_qc.pl /usr/local/bin
	/data/bnf/sw/sentieon/sentieon-genomics-202010.01 /opt
	/data/bnf/sw/melt/MELTv2.1.5/MELT.jar /opt/
	
%post
	mkdir /usr/share/man/man1/
	rm -rf /var/lib/apt/lists/*
	apt -y clean
	apt -y update
	apt -y install build-essential make
	apt -y install graphicsmagick-imagemagick-compat libtbb2

	/opt/conda/bin/conda install mamba -n base -c conda-forge

	/opt/conda/bin/mamba env create -n main-env --file /environment.yml
	/opt/conda/bin/mamba env create -n java8 --file /environment_java8.yml
	/opt/conda/bin/mamba env create -n py2 --file /environment_py2.yml
	/opt/conda/bin/mamba env create -n sambamba --file /environment_sambamba.yml
	/opt/conda/bin/mamba env create -n old-cnvkit --file /environment_old-cnvkit.yml
	/opt/conda/bin/conda clean -a
	
	/opt/conda/envs/main-env/bin/cpanm JSON

	git clone https://github.com/Clinical-Genomics-Lund/qc_sentieon.git
	cd qc_sentieon
	git checkout c453713628a52125e72f5cadb7a0d1a44b058132
	cp qc_sentieon.pl /opt/conda/bin/.

	cd / && git clone https://github.com/J35P312/SVDB
	cd SVDB && git checkout 2.2.0
	/opt/conda/envs/main-env/bin/pip install --editable .

