Bootstrap: docker
From: debian:latest

%labels
    MAINTAINER icaoberg
    EMAIL icaoberg@psc.edu
    SUPPORT help@psc.edu
    REPOSITORY http://github.com/pscedu/singularity-gent
    COPYRIGHT Copyright © 2021-2023 Pittsburgh Supercomputing Center. All Rights Reserved. 
    VERSION 1.0.0

%post
    apt update
    apt install -y gnuplot gfortran git
    git clone https://github.com/icaoberg/GeNT.git
    cd GeNT && gfortran -o gent gent.for && \
         cp gent /usr/local/bin && \
         cp gnuplot.script /usr/local/bin
    cd .. && rm -rfv GeNT

%runscript
    gent "$@"    
