Bootstrap: docker
From: alpine:edge

%labels
    MAINTAINER icaoberg
    EMAIL icaoberg@psc.edu
    SUPPORT help@psc.edu
    REPOSITORY https://github.com/pscedu/singularity-samtools
    COPYRIGHT Copyright © 2021 Pittsburgh Supercomputing Center. All Rights Reserved.
    VERSION 1.11.0

%post 
    apk update  # Ensure the package list is up to date
    apk add autoconf automake make gcc musl-dev perl bash zlib-dev bzip2-dev xz-dev curl-dev libressl-dev ncurses-dev wget
    wget -nc https://github.com/samtools/samtools/releases/download/1.11/samtools-1.11.tar.bz2
    tar -xvf samtools-1.11.tar.bz2 && rm -f samtools-1.11.tar.bz2
    mv samtools-1.11 /opt/
    cd /opt/samtools-1.11
    ./configure
    make
    make install
