Bootstrap: docker
From: quay.io/biocontainers/methylpy:1.4.3--py37h41a55b7_0

%labels
    AUTHOR icaoberg
    EMAIL icaoberg@psc.edu
    WEBSITE https://github.com/pscedu/singularity-methylpy
    COPYRIGHT Copyright © 2021 Pittsburgh Supercomputing Center. All Rights Reserved.
    VERSION 1.4.3
