# Copyright (c) 2020 NVIDIA Corporation.  All rights reserved. 

Bootstrap: docker
FROM: nvcr.io/nvidia/nvhpc:20.11-devel-cuda_multi-ubuntu20.04

%environment
    export XDG_RUNTIME_DIR=
    export LIBRARY_PATH="$LD_LIBRARY_PATH:/usr/local/lib:/opt/nvidia/hpc_sdk/Linux_x86_64/20.11/cuda/11.0/lib64/"
    export PATH="/opt/nvidia/nsight-systems/2020.5.1/bin:/opt/nvidia/nsight-compute/2020.2.1:/opt/nvidia/hpc_sdk/Linux_x86_64/20.11/cuda/11.0/include:/usr/local/bin:/opt/anaconda3/bin:/usr/bin:$PATH"


%post
    build_tmp=$(mktemp -d) && cd ${build_tmp}

    export PATH=/opt/nvidia/hpc_sdk/Linux_x86_64/20.11/compilers/bin/:$PATH

    apt-get -y update
    apt-get -y dist-upgrade 
    DEBIAN_FRONTEND=noninteractive apt-get -yq install   --no-install-recommends \
	    m4 vim-nox emacs-nox nano zip \
 	    python3 python3-pip python3-setuptools git-core inotify-tools \
	    curl git-lfs \
	    build-essential
    rm -rf /var/lib/apt/cache/* 

    pip3 install --upgrade pip
    pip3 install --no-cache-dir jupyter
    pip3 install jupyter netcdf4

# NVIDIA nsight-systems-2020.5.1 ,nsight-compute-2
    apt-get update -y && \
        DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
        apt-transport-https \
        ca-certificates \
        gnupg \
        wget && \
        apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys F60F4B3D7FA2AF80 && \
        echo "deb https://developer.download.nvidia.com/devtools/repos/ubuntu2004/amd64/ /" >> /etc/apt/sources.list.d/nsight.list &&\
        apt-get update -y

    DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends nsight-systems-2020.5.1 nsight-compute-2020.2.1 

    cd /
    rm -rf ${build_tmp}

%files
    English/ /labs

%runscript
    "$@"

%labels
    AUTHOR bharatk
