#!/bin/bash
#
# Christophe Demay <christophe.demay@chru-lille.fr>
# 2018/04/24: initial version
BootStrap: docker
From: ensemblorg/ensembl-vep:release_96.0 
%labels
  MAINTAINER christophe.demay@chru-lille.fr
  VERSION 96.0

%environment

%help

%post
    

