bootstrap:docker
From:ubuntu:xenial


%setup
    cp gis_dependency.makefile $SINGULARITY_ROOTFS/tmp/
    cp sources.list $SINGULARITY_ROOTFS/etc/apt/sources.list

%environment
    GISBASE=/opt/eemt/grass-7.2.1
    GRASS_PROJSHARE=/usr/share/proj
    LD_LIBRARY_PATH=/opt/eemt/lib:/opt/eemt/grass-7.2.1/lib
    PATH=/opt/eemt/bin:/opt/eemt/grass-7.2.1/bin:$PATH
    PYTHONPATH=/opt/eemt/lib/python2.7/site-packages
    export GISBASE GRASS_PROJSHARE LD_LIBRARY_PATH PATH PYTHONPATH

%post

    apt-get update && apt-get upgrade -y

    apt-get update && apt-get install -y \
        bison \
        build-essential \
        ccache \
        checkinstall \
        cmake \
        curl \
        ffmpeg2theora \
        flex \
        gcc \
        gettext \
        ghostscript \
        libavcodec-dev \
        libavformat-dev \
        libav-tools \
        libavutil-dev \
        libboost-program-options-dev \
        libboost-thread-dev \
        libcairo2 \
        libcairo2-dev \
        libffmpegthumbnailer-dev \
        libfftw3-3 \
        libfftw3-dev \
        libfreetype6-dev \
        libgcc1 \
        libglu1-mesa-dev \
        libgsl-dev \
        libgtk2.0-dev \
        libgtkmm-3.0-dev \
        libjasper-dev \
        liblas-c-dev \
        libncurses5-dev \
        libnetcdf-dev \
        libperl-dev \
        libpng12-dev \
        libpnglite-dev \
        libpq-dev \
        libproj-dev \
        libreadline6 \
        libreadline6-dev \
        libsqlite3-dev \
        libswscale-dev \
        libtiff5-dev \
        libwxbase3.0-dev   \
        libwxgtk3.0-dev \
        libxmu-dev \
        libxmu-dev \
        libzmq3-dev \
        netcdf-bin \
        openjdk-8-jdk \
        pkg-config \
        proj-bin \
        proj-data \
        python \
        python-dateutil \
        python-dev \
        python-numpy \
        python-opengl \
        python-wxgtk3.0 \
        python-wxtools \
        python-wxversion \
        rsync \
        sqlite3 \
        subversion \
        swig \
        unzip \
        vim \
        wget \
        wx3.0-headers \
        wx-common \
        zlib1g-dev \

    cd /tmp && \
       wget -nv http://ccl.cse.nd.edu/software/files/cctools-6.0.16-source.tar.gz && \
       tar xzf cctools-6.0.16-source.tar.gz && \
       cd cctools-6.0.16-source && \
       ./configure --prefix=/opt/eemt && \
       make && \
       make install

    cd /tmp && make -f gis_dependency.makefile

    rm -rf /tmp/build-dir /tmp/cctools*

    echo "Updating library paths"
    cd /etc/ld.so.conf.d
    echo "/opt/eemt/lib" >eemt.conf
    echo "/opt/eemt/lib64" >>eemt.conf
    echo "/opt/eemt/grass-7.2.1/lib" >grass.conf
    ldconfig

    # build info
    echo "Timestamp:" `date --utc` | tee /image-build-info.txt

