Bootstrap: docker
From: perl:5.32.1

%labels
    MAINTAINER icaoberg
    EMAIL icaoberg@psc.edu
    SUPPORT help@psc.edu
    REPOSITORY http://gitub.com/pscedu/singularity-genemark-es
    COPYRIGHT Copyright © 2021 Pittsburgh Supercomputing Center. All Rights Reserved.    
    VERSION 4.65

%environment
    export LANGUAGE=en_US.UTF-8
    export LC_ALL=C
    export PATH=$PATH:/opt/gmes_linux_64

%post
    export DEBIAN_FRONTEND=noninteractive
    apt update && apt-get install -y locales libipc-run3-perl python3 libconfig-yaml-perl
    locale-gen en_US.UTF-8
    cpan install CPAN::DistnameInfo
    cpan install Parallel::ForkManager
    cpan install YAML
    cpan install Config::YAML
    cpan install Hash::Merge
    cpan install Parallel::ForkManager
    cpan install MCE::Mutex
    cpan install Thread::Queue
    cpan install threads
    cpan install Math::Utils
    cd /opt
    wget http://topaz.gatech.edu/GeneMark/tmp/GMtool_04yHM/gmes_linux_64.tar.gz
    wget http://topaz.gatech.edu/GeneMark/tmp/GMtool_04yHM/gm_key_64.gz
    tar -xvf gmes_linux_64.tar.gz && rm -f gmes_linux_64.tar.gz
    cd /opt/gmes_linux_64
    chmod +x *.py
    chmod +x *.pl
    sed -i 's|/usr/bin/perl|/usr/local/bin/perl|g' *.pl
    sed -i 's|/usr/bin/perl|/usr/local/bin/perl|g' *.py
