#!/bin/bash
#
# Fabrice Bonte <fabrice.bonte@chru-lille.fr>
# 03/12/2020: initial version
BootStrap: docker
From: ensemblorg/ensembl-vep:release_102.0 
%labels
  MAINTAINER fabrice.bonte@chru-lille.fr
  VERSION 102.0

%environment

%help

%post
    

