Bootstrap:docker
From:nfcore/base:latest

%labels
	MAINTAINER Isak Sylvin <isak.sylvin@scilifelab.se>
	DESCRIPTION Singularity container for JASEN microbiology WGS pipeline
	VERSION 0.1.0

%environment
        export PYTHONNOUSERSITE=True
        export PATH="/opt/conda/bin:/usr/bin:$PATH"
        export PATH="/opt/conda/envs/jasen/bin:$PATH"
        export PYTHONPATH="/opt/conda/envs/jasen/lib/python3.7/site-packages:/opt/conda/envs/jasen/lib"
        export BASH_ENV="/conda_init.sh:$BASH_ENV"
	export PICARD_HOME=/opt/conda/envs/jasen/share/picard-2.20.3-0/
	export PERL5LIB=$PERL5LIB:/opt/conda/envs/jasen/lib/site_perl/5.26.2/
        export TMPDIR=/tmp
        export TEMPDIR=/tmp
	umask 0002

%files
        conda_init.sh /
        ../nextflow.config /

%post
        apt -y update
        apt -y install build-essential make curl unzip locales
        ln -s /opt/conda/lib/libcrypto.so.1.1 /opt/conda/lib/libcrypto.so.1.0.0
        locale-gen en_US.UTF-8
        localedef -i en_US -c -f UTF-8 -A /usr/share/locale/locale.alias en_US.UTF-8
        mkdir -p /scratch/nxf /scratch/sing /scratch/tmp /external /out
 

        /usr/bin/git clone --recurse-submodules --single-branch --branch master  https://github.com/genomic-medicine-sweden/JASEN.git
        /opt/conda/bin/conda env create -f JASEN/container/environment.yml
        ln -s /opt/conda/envs/jasen/lib/libcrypto.so.1.1 /opt/conda/envs/jasen/lib/libcrypto.so.1.0.0

        # Conda setup attempts
        #/bin/cat conda_init.sh >> ~/.bashrc
        /opt/conda/bin/conda init bash
        . /opt/conda/etc/profile.d/conda.sh
        conda config --set auto_activate_base true

        # Installation of nextFlow
        mkdir -p /usr/share/man/man1
        apt -y install default-jre openjdk-11-jdk
        . /opt/conda/bin/activate jasen 
        /usr/bin/curl -s https://get.nextflow.io | /bin/bash
        . /opt/conda/bin/deactivate
        /bin/chmod 0755 nextflow
        /bin/mv /nextflow /bin/ 

%runscript
        . /opt/conda/etc/profile.d/conda.sh
        . /opt/conda/bin/activate jasen
	exec "$@"`
        . /opt/conda/bin/deactivate
