Bootstrap: docker
From: quay.io/biocontainers/picard:2.23.2--0

%labels
    AUTHOR icaoberg
    EMAIL icaoberg@psc.edu
    WEBSITE http://www.andrew.cmu.edu/~icaoberg
    VERSION 2.23.2

%post
   rm /etc/resolv.conf

####################################################################################
