Bootstrap: docker
From: quay.io/biocontainers/picard:2.23.2--0

%labels
    AUTHOR icaoberg
    EMAIL icaoberg@psc.edu
    SUPPORT help@psc.edu
    REPOSITORY http://github.com/icaoberg/singularity-picard
    COPYRIGHT Copyright © 2021 Pittsburgh Supercomputing Center. All Rights Reserved. 
    VERSION 2.23.2
