Bootstrap: docker
From: python:3.8-alpine

%labels
    MAINTAINER icaoberg
    EMAIL icaoberg@psc.edu
    SUPPORT help@psc.edu
    REPOSITORY http://gitub.com/pscedu/singularity-visidata
    COPYRIGHT Copyright © 2021 Pittsburgh Supercomputing Center. All Rights Reserved.   
    VERSION 2.4

%environment
    export TERM="xterm-256color"

%post
    apk update
    apk add git
    pip install requests python-dateutil wcwidth tabulate
    mkdir -p /opt/visidata
    git clone https://github.com/saulpw/visidata.git
    cd visidata
    sh -c 'yes | pip install -vvv .'
    rm -rfv visidata
