bootstrap: docker
from: nvidia/cuda:9.2-devel-centos7

%environment

export PATH=/opt/ICON_GPU_v1.2.9_CentOS64/bin:/usr/local/cuda/bin/:$PATH
export LIBRARY_PATH=/usr/local/cuda/lib64/stubs
export LD_LIBRARY_PATH=/usr/local/nvidia/lib:/usr/local/nvidia/lib64:$LD_LIBRARY_PATH

%post

yum install -y make gcc
export PATH=/usr/local/cuda/bin/:$PATH
export LIBRARY_PATH=/usr/local/cuda/lib64/stubs
export LD_LIBRARY_PATH=/usr/local/nvidia/lib:/usr/local/nvidia/lib64:$LD_LIBRARY_PATH
curl http://feilab.ibp.ac.cn/software/ICON/ICON-GPU_v1.2.9_CentOS64.tar.gz | tar xvz -C /opt/
cd /opt/ICON_GPU_v1.2.9_CentOS64/
sh install
