Bootstrap: library
From: debian:bullseye

%help
    See the README.md file in /doc

%setup
    mkdir -p ${SINGULARITY_ROOTFS}/app
    mkdir -p ${SINGULARITY_ROOTFS}/proj

%environment
    export LC_ALL=C.UTF-8

%files
    wsgi.py /app
    app.py /app
    gunicorn_config.py /proj
    flask_stub.conf /proj

%post
    export DEBIAN_FRONTEND=noninteractive
    export TZ="America/Los_Angeles"

    apt-get update
    apt-get upgrade -y

    # Various standard packaged software
    apt-get install -y ca-certificates apache2 gunicorn python3-flask python3-requests less

    # Clean the apt files
    apt-get clean
    rm -r /var/lib/apt/lists/*

    rm /etc/apache2/sites-enabled/000-default.conf
    ln -s /proj/flask_stub.conf /etc/apache2/sites-enabled/
    a2enmod proxy_http

%startscript
    /etc/init.d/apache2 start
    cd /app
    /usr/bin/gunicorn --config /proj/gunicorn_config.py wsgi:app
