Bootstrap: docker-daemon
From: icaoberg/braker2:2.1.6

%labels
    MAINTAINER icaoberg
    EMAIL icaoberg@psc.edu
    SUPPORT help@psc.edu
    REPOSITORY https://github.com/pscedu/singularity-braker2
    COPYRIGHT Copyright © 2022 Pittsburgh Supercomputing Center. All Rights Reserved.
    VERSION 2.1.6
