BootStrap: library
From: granek/duke-chsi-informatics/singularity-rnaseq:0005

%labels
    Maintainer Josh Granek
    Image_Name rna_enrichment
    Image_Version rna_enrichment_0005

%post
  export DEBIAN_FRONTEND=noninteractive
  apt-get update
  apt-get install -y --no-install-recommends \
    uuid-runtime # need for vdb-config
    
  Rscript -e "install.packages(pkgs = c('rstatix','ggpubr','rentrez','R.utils'), repos='https://mirror.las.iastate.edu/CRAN/', dependencies=TRUE, clean = TRUE)"
  pip3 install --no-cache-dir \
    RSeQC

  #------------------
  # Install Bioconductor Packages
  #------------------
  Rscript -e "if (!requireNamespace('BiocManager')){install.packages('BiocManager')}; BiocManager::install(); BiocManager::install(c('GEOquery','CoverageView','bamsignals','RCAS'))"

  mkdir -p /space

  #------------------
  # Final apt cleanup
  #------------------
  apt-get clean
  rm -rf /var/lib/apt/lists/*
