Bootstrap:docker
From:nfcore/base:1.8

%labels
	MAINTAINER Viktor henmyr <viktor.henmyr@skane.se>
	DESCRIPTION Singularity container for CMD WGS pipeline
	VERSION 0.0.1

%environment
    PATH=/opt/conda/envs/py3-env/bin:/REViewer/build/install/bin:/opt/bin:$PATH
	export PERL5LIB=$PERL5LIB:/opt/conda/envs/CMD-WGS/lib/site_perl/5.26.2/
	export PERL5LIB=$PERL5LIB:/opt/conda/envs/CMD-WGS/lib/site_perl/5.26.2/x86_64-linux-thread-multi/
	export PERL5LIB=$PERL5LIB:/opt/bin/
	umask 0002

%files
    

%post
	rm -rf /var/lib/apt/lists/*
	apt -y clean
	apt -y update
	apt -y install libz-dev build-essential gettext cmake libxml2-dev libcurl4-openssl-dev libssl-dev make libbz2-dev liblzma-dev


	/opt/conda/bin/conda create -n py3-env python=3
	/opt/conda/bin/conda clean -a
    . /opt/conda/bin/activate py3-env

    cd / && git clone https://github.com/moonso/stranger.git
	cd stranger && git checkout c475cf0661dc0f35dd224d1d9015ca075b4146fd
	/opt/conda/envs/py3-env/bin/pip install --editable .