Bootstrap: docker
From: datascienceworkshops/data-science-at-the-command-line

#Bootstrap: shub
#From: singularityhub/centos

%labels
AUTHOR abhi18av

%help
data-science-at-the-command-line

%runscript 

%post
