#!/bin/bash
#
# Christophe Demay <christophe.demay@chru-lille.fr>
# 2018/05/11: initial version
BootStrap: docker
From: phusion/baseimage:0.11
%labels
  MAINTAINER christophe.demay@chru-lille.fr
  VERSION 75

%environment
  PATH=/opt/vep/src/ensembl-tools-release-75/scripts/variant_effect_predictor/:$PATH
  export  LC_ALL=en_US.UTF-8
  export  LANGUAGE=en_US.UTF-8

%help

%post
	echo 'debconf debconf/frontend select Noninteractive' | debconf-set-selections

  apt-get update
  apt-get -y install \
    build-essential \
    cpanminus \
    curl \
    wget \
    unzip \
    perl \
    perl-base \
    libdbd-mysql-perl \
    libarchive-zip-perl \
    libdbi-perl \
    libarchive-extract-perl \
    libcgi-pm-perl \
    libbio-perl-perl \
    tabix 
         
  mkdir -p /opt/vep/src
       
       
  #cpanm   Archive::Zip   DBI  #DBD::mysql
  #cpanm Archive::Extract Archive::Zip CGI Bio::PrimarySeqI DBI  XML::DOM XML::Parser Net::HTTP
  # Bio::Perl 
  # LWP::Simple LWP::Protocol::https

  cd /opt/vep/src
  wget https://github.com/Ensembl/ensembl-tools/archive/release/75.zip
  unzip 75.zip
  
  cd /opt/vep/src/ensembl-tools-release-75/scripts/variant_effect_predictor/
  ln -s variant_effect_predictor.pl vep
  chmod u+x *.pl
  ./INSTALL.pl -a a -b 'https://github.com/bioperl/bioperl-live/archive/release-1-6-924.tar.gz'
  
  rm /opt/vep/src/75.zip