BootStrap: docker
From: alpine:latest

%labels
  Maintainer Christian Dietrich
  SAMtools_Version 1.9

%apprun samtools
  exec samtools "${@}"
  
%apprun ace2sam
  exec ace2sam "${@}"

%apprun blast2sam.pl
  exec blast2sam.pl "${@}"

%apprun bowtie2sam.pl
  exec bowtie2sam.pl "${@}"

%apprun export2sam.pl
  exec export2sam.pl "${@}"

%apprun interpolate_sam.pl
  exec interpolate_sam.pl "${@}"

%apprun maq2sam-long
  exec maq2sam-long "${@}"

%apprun maq2sam-short
  exec maq2sam-short "${@}"

%apprun md5fa
  exec md5fa "${@}"

%apprun md5sum-lite
  exec md5sum-lite "${@}"

%apprun novo2sam.pl
  exec novo2sam.pl "${@}"

%apprun plot-bamstats
  exec plot-bamstats "${@}"

%apprun psl2sam.pl
  exec psl2sam.pl "${@}"

%apprun sam2vcf.pl
  exec sam2vcf.pl "${@}"

%apprun samtools.pl
  exec samtools.pl "${@}"

%apprun seq_cache_populate.pl
  exec seq_cache_populate.pl "${@}"

%apprun soap2sam.pl
  exec soap2sam.pl "${@}"

%apprun varfilter.py
  exec varfilter.py "${@}"

%apprun wgsim
  exec wgsim "${@}"

%apprun wgsim_eval.pl
  exec wgsim_eval.pl "${@}"

%apprun zoom2sam.pl
  exec zoom2sam.pl "${@}"

%runscript
  exec samtools "${@}"

%post
  # Get dependencies
  apk update && apk add make gcc g++ ncurses-dev ncurses-libs zlib-dev zlib bzip2-dev libbz2 xz-dev xz-libs curl-dev libcurl python2 perl

  # Install SAMtools
  wget -q -O - https://github.com/samtools/samtools/releases/download/1.9/samtools-1.9.tar.bz2 | tar -C /tmp -xjf -
  cd /tmp/samtools-*
  make -j$(nproc) install

  # Clean up
  apk del make gcc g++ ncurses-dev zlib-dev bzip2-dev xz-dev curl-dev libcurl
  rm -rf /var/cache/apk/*
