Bootstrap: docker
From: debian:stretch

%labels
    AUTHOR icaoberg
    EMAIL icaoberg@psc.edu
    SUPPORT help@psc.edu
    WEBSITE http://github.com/icaoberg/singularity-raw2ometiff
    COPYRIGHT Copyright © 2021-2022 Pittsburgh Supercomputing Center. All Rights Reserved. 
    VERSION 3.0.0

%environment
    export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64/

%post
    apt update
    apt install -y libblosc1 wget unzip openjdk-8-jdk
    cd /opt/
    wget -nc https://github.com/glencoesoftware/raw2ometiff/releases/download/v0.3.0/raw2ometiff-0.3.0.zip
    unzip raw2ometiff-0.3.0.zip && rm -f raw2ometiff-0.3.0.zip
    ln -s /opt/raw2ometiff-0.3.0/bin/raw2ometiff /usr/local/bin/raw2ometiff
    apt remove -y wget unzip
    apt clean

%runscript
    /usr/local/bin/raw2ometiff
