Bootstrap: docker
From: gnuoctave/octave:7.2.0

%labels
    MAINTAINER icaoberg
    EMAIL icaoberg@psc.edu
    SUPPORT help@psc.edu
    WEBSITE http://github.com/pscedu/singularity-octave
    COPYRIGHT Copyright © 2022, Pittsburgh Supercomputing Center. All Rights Reserved.
    VERSION 7.2.0

%post
    apt-get update
    apt-get install -y gnuplot pandoc vim imagemagick ffmpeg
    apt-get clean
    apt-get autoclean
