Bootstrap: docker
From: alpine:edge

%labels
    MAINTAINER icaoberg
    EMAIL icaoberg@psc.edu
    SUPPORT help@psc.edu
    REPOSITORY http://github.com/pscedu/singularity-graphviz
    COPYRIGHT Copyright 2024 Pittsburgh Supercomputing Center. All Rights Reserved. 
    VERSION 9.0.0-r1

%post
    apk update
    apk add graphviz

%runscript
    dot "$@"
