Bootstrap: docker
From: continuumio/anaconda3

%labels
    AUTHOR icaoberg
    EMAIL icaoberg@psc.edu
    SUPPORT help@psc.edu
    REPOSITORY http://gitub.com/pscedu/singularity-rich-cli
    COPYRIGHT Copyright © 2021-2022 Pittsburgh Supercomputing Center. All Rights Reserved.
    VERSION 1.8.0

%post
    apt update
    conda install -c conda-forge rich-cli
