Bootstrap: docker
From: debian:buster

%labels
    MAINTAINER icaoberg
    EMAIL icaoberg@psc.edu
    SUPPORT help@psc.edu
    REPOSITORY https://github.com/icaoberg/singularity-salmon
    COPYRIGHT Copyright © 2021 Pittsburgh Supercomputing Center. All Rights Reserved.  
    VERSION 1.5.2

%post 
    apt-get update && \
    apt remove -y libcurl4 && \
    apt-get install -y --no-install-recommends git gcc make g++ libboost-all-dev liblzma-dev libbz2-dev ca-certificates zlib1g-dev libcurl4-openssl-dev curl unzip autoconf apt-transport-https ca-certificates gnupg software-properties-common wget && \
    apt-get clean
    wget -O - https://apt.kitware.com/keys/kitware-archive-latest.asc 2>/dev/null | apt-key add -
    apt-add-repository 'deb https://apt.kitware.com/ubuntu/ bionic main'
    apt-get update
    apt-key --keyring /etc/apt/trusted.gpg del C1F34CDD40CD72DA
    apt-get install kitware-archive-keyring
    apt-get install -y cmake
    wget -nc https://github.com/COMBINE-lab/salmon/releases/download/v1.5.2/salmon-1.5.2_linux_x86_64.tar.gz
    tar -xzf salmon-1.5.2_linux_x86_64.tar.gz
    cd salmon-1.5.2_linux_x86_64
    mv bin/salmon /usr/bin/
    mv lib/* /usr/lib/
