Bootstrap: docker
From: quay.io/biocontainers/hisat2:2.2.1--he1b5a44_2

%labels
    AUTHOR icaoberg
    EMAIL icaoberg@psc.edu
    SUPPORT help@psc.edu
    REPOSITORY https://github.psc.edu/icaoberg/singularity-hisat2
    COPYRIGHT Copyright © 2021 Pittsburgh Supercomputing Center. All Rights Reserved.
    VERSION 2.2.1

