Bootstrap: shub
From: mkandes/centos:latest

%labels

    APPLICATION_NAME centos + mvapich
    APPLICATION_VERSION 7.7.1908 + 2.3.2
    APPLICATION_URL https://mvapich.cse.ohio-state.edu

    SINGULARITY_VERSION 2.6.1
    SINGULARITY_IMAGE_SIZE 4096

    AUTHOR_NAME Marty Kandes
    AUTHOR_EMAIL mkandes@sdsc.edu

    LAST_UPDATED 20200408

%setup

%environment

    # Set paths to MVAPICH2 binaries and libraries
    export PATH="/opt/mvapich2-2.3.2/bin:${PATH}"
    export LD_LIBRARY_PATH="/opt/mvapich2-2.3.2/lib:${LD_LIBRARY_PATH}"

    # Set paths to OSU Microbenchmarks binaries
    export PATH="/opt/omb-5.6.2/collective:${PATH}"
    export PATH="/opt/omb-5.6.2/one-sided:${PATH}"
    export PATH="/opt/omb-5.6.2/pt2pt:${PATH}"
    export PATH="/opt/omb-5.6.2/startup:${PATH}"

%post -c /bin/bash

    # Set operating system mirror URL
    export MIRRORURL='http://mirror.centos.org/centos-7/7/os/x86_64'

    # Set operating system version
    export OSVERSION='7'

    # Set system locale
    export LC_ALL=C

    # Set path to miniconda
    #export PATH="/opt/miniconda3/bin:${PATH}"

    # Update all software packages to their latest versions
    yum -y check-update && yum -y update

    # Install basic drivers for user space access to Ethernet, RDMA,
    # and Infiniband. See https://community.mellanox.com/docs/DOC-2431
    yum -y install dkms
    yum -y install infiniband-diags
    yum -y install infiniband-diags-devel
    yum -y install libibverbs
    yum -y install libibverbs-devel
    yum -y install ibacm
    yum -y install librdmacm
    yum -y install librdmacm-devel
    yum -y install libmlx4
    yum -y install libmlx5
    yum -y install mstflint
    yum -y install libibcm
    yum -y install libibmad
    yum -y install libibmad-devel
    yum -y install libibumad
    yum -y install libibumad-devel
    yum -y install opensm
    yum -y install srptools

    # Install additional tools
    yum -y install ibutils
    yum -y install libibverbs-utils
    yum -y install librdmacm-utils
    yum -y install perftest
    yum -y install numactl

    # Install libnl
    yum -y install libnl3
    yum -y install libnl3-devel

    # Install mvapich2 (build) dependencies
    yum -y install bison

    cd /tmp

    # Download, build, and install mvapich2
    wget http://mvapich.cse.ohio-state.edu/download/mvapich/mv2/mvapich2-2.3.2.tar.gz
    tar -xzvf mvapich2-2.3.2.tar.gz
    cd mvapich2-2.3.2
    ./configure --prefix=/opt/mvapich2-2.3.2
    make
    make install

    # Set paths to MVAPICH2 binaries and libraries
    export PATH="/opt/mvapich2-2.3.2/bin:${PATH}"
    export LD_LIBRARY_PATH="/opt/mvapich2-2.3.2/lib:${LD_LIBRARY_PATH}"

    cd /tmp

    # Download, build, and install OSU Microbenchmarks
    wget http://mvapich.cse.ohio-state.edu/download/mvapich/osu-micro-benchmarks-5.6.2.tar.gz
    tar -xzvf osu-micro-benchmarks-5.6.2.tar.gz
    cd osu-micro-benchmarks-5.6.2
    ./configure --prefix='/opt/omb-5.6.2' CC='mpicc' CXX='mpicxx'
    make
    make install

    # Reorganize OSU Microbenchmarks directory structure
    cd /opt/omb-5.6.2
    mv libexec/osu-micro-benchmarks/mpi/collective ./
    mv libexec/osu-micro-benchmarks/mpi/one-sided ./
    mv libexec/osu-micro-benchmarks/mpi/pt2pt ./
    mv libexec/osu-micro-benchmarks/mpi/startup ./
    rm -rf libexec

    # Cleanup
    package-cleanup -q --leaves | xargs -l1 yum -y remove
    yum -y clean all

    # Update database for mlocate
    updatedb

%files

%runscript

%test
