bootstrap: docker
from: detlab/cdms-jupyterlab:0.1.6

%environment

export PATH=/packages/root6.12/bin:/opt/rh/rh-python36/root/usr/bin${PATH:+:${PATH}}
export LD_LIBRARY_PATH=/packages/root6.12/lib:/opt/rh/rh-python36/root/usr/lib64${LD_LIBRARY_PATH:+:${LD_LIBRARY_PATH}}
export MANPATH=/packages/root6.12/man:/opt/rh/rh-python36/root/usr/share/man:$MANPATH
export PKG_CONFIG_PATH=/opt/rh/rh-python36/root/usr/lib64/pkgconfig${PKG_CONFIG_PATH:+:${PKG_CONFIG_PATH}}
export XDG_DATA_DIRS="/opt/rh/rh-python36/root/usr/share:${XDG_DATA_DIRS:-/usr/local/share:/usr/share}"
export LIBPATH=/packages/root6.12/lib
export JUPYTER_PATH=/packages/root6.12/etc/notebook
export ROOTSYS=/packages/root6.12
export DYLD_LIBRARY_PATH=/packages/root6.12/lib
export PYTHONPATH=/packages/root6.12/lib
export SHLIB_PATH=/packages/root6.12/lib
export CMAKE_PREFIX_PATH=/packages/root6.12


%runscript

source /packages/root6.12/bin/thisroot.sh

