Bootstrap: docker
From: debian:latest

%labels
    MAINTAINER icaoberg
    EMAIL icaoberg@psc.edu
    WEBSITE http://gitub.com/pscedu/singularity-blast
    COPYRIGHT Copyright © 2021 Pittsburgh Supercomputing Center. All Rights Reserved.
    VERSION 2.13.0

%post
    apt update && apt install -y build-essential wget cpio
    cd /opt
    wget https://ftp.ncbi.nlm.nih.gov/blast/executables/blast+/LATEST/ncbi-blast-2.13.0+-src.tar.gz
    tar -xvf ncbi-blast-2.13.0+-src.tar.gz && rm -f ncbi-blast-2.13.0+-src.tar.gz
    cd ncbi-blast-2.13.0+-src/c++
    ./configure
    make
    make install
