Bootstrap: docker
From: continuumio/miniconda3:latest
Stage: condabuild

%labels
authors="Zohaib Anwar"
description="Docker image containing all requirements for the nf-ncov-voc"

%post
/opt/conda/bin/conda create --name upcoastv-env && \
    conda config --append channels default && \
    conda config --append channels bioconda  && \
    conda config --append channels conda-forge  && \
    conda install mamba -n base -c conda-forge && \
    mamba install python \
    biopython=1.78 \
    pandas=1.2.4 \
    bwa=0.7.17 \
    samtools=1.12 \
    bcftools=1.12 \
    ivar=1.3.1 \
    csvtk=0.23 \
    graphviz=2.47.1 \
    bbmap=38.90 \
    seqtk=1.3 \
    htslib=1.12 \
    minimap2=2.18

Bootstrap: docker
From: debian:buster-slim
Stage: final

%post
apt-get update && \
apt-get install -y git procps python3-pip && \
pip install cyvcf
apt-get clean -y

%environment
export PATH=/opt/conda/envs/nf-ncov-voc/bin:$PATH
