Bootstrap: docker
From: nvidia/cuda:8.0-cudnn5-devel-ubuntu16.04

%environment
	#Environment variables

	#Add CUDA paths
	CPATH="/usr/local/cuda/include:$CPATH"
	PATH="/usr/local/cuda/bin:$PATH"
	LD_LIBRARY_PATH="/usr/local/cuda/lib64:$LD_LIBRARY_PATH"
	CUDA_HOME="/usr/local/cuda"

	#Export torch paths
	#Modified from torch-activate
	LUA_PATH="/home/$USER/.luarocks/share/lua/5.1/?.lua;/home/$USER/.luarocks/share/lua/5.1/?/init.lua;/usr/local/torch/install/share/lua/5.1/?.lua;/usr/local/torch/install/share/lua/5.1/?/init.lua;./?.lua;/usr/local/torch/install/share/luajit-2.1.0-beta1/?.lua;/usr/local/share/lua/5.1/?.lua;/usr/local/share/lua/5.1/?/init.lua"
	LUA_CPATH="/home/$USER/.luarocks/lib/lua/5.1/?.so;/usr/local/torch/install/lib/lua/5.1/?.so;./?.so;/usr/local/lib/lua/5.1/?.so;/usr/local/lib/lua/5.1/loadall.so"
	PATH=/usr/local/torch/install/bin:$PATH
	LD_LIBRARY_PATH=/usr/local/torch/install/lib:$LD_LIBRARY_PATH
	DYLD_LIBRARY_PATH=/usr/local/torch/install/lib:$DYLD_LIBRARY_PATH
	LUA_CPATH='/usr/local/torch/install/lib/?.so;'$LUA_CPATH

	export PATH LD_LIBRARY_PATH CPATH LUA_PATH LUA_CPATH DYLD_LIBRARY_PATH CUDA_HOME

%setup
	#Runs on host
	#The path to the image is $SINGULARITY_ROOTFS



%post
	#Post setup script

	#Default mount paths
	mkdir /scratch /data /shared /fastdata


	#Updating and getting required packages
	apt-get update
	apt-get install -y wget git cmake
	apt-get install -y libreadline-dev
	apt-get install -y unzip

	#Creates a build directory
	BUILD_ROOT="/usr/local/torch/"
	INSTALL_ROOT="$BUILD_ROOT/install"
	PATH="$INSTALL_ROOT/bin:$PATH"
	LD_LIBRARY_PATH="$INSTALL_ROOT/lib:$LD_LIBRARY_PATH"

	#Prefix flag makes torch install at this directory
	PREFIX="$INSTALL_ROOT"

	export BUILD_ROOT INSTALL_ROOT PATH LD_LIBRARY_PATH PREFIX 

	mkdir -p $BUILD_ROOT
	
	#Goes to the build root
	cd $BUILD_ROOT


	#Download and install torch
	git clone https://github.com/torch/distro.git /usr/local/torch --recursive
	cd /usr/local/torch
	#Remove all the sudo commands from install deps
	sed -i  "s/sudo //" install-deps
	bash install-deps
	./install.sh

	#Other requested packages to install
	luarocks install --server=http://luarocks.org/dev paths
	luarocks install tds
	luarocks install bit32

	apt install zlib1g-dev
	luarocks install lua-zlib


%runscript
	#Executes with the singularity run command
	#delete this section to use existing docker ENTRYPOINT command


%test
	#Test that script is a success
