Bootstrap: docker
From: ubuntu:20.04
%labels
MAINTAINER  Edoardo Apra <edoardo.apra@pnnl.gov>

%setup
    ls -la  ${GITHUB_WORKSPACE}
    export CACHEDIR=${GITHUB_WORKSPACE}/../../../cache
    ls -lrt ${CACHEDIR} || true
    ls -la  ${CACHEDIR}/ || true
    ls -la  ${CACHEDIR}/ompi || true
    ls -la  ${CACHEDIR}/ompi/lib || true
    ls -la  ${CACHEDIR}/simint.l5_p5_d1.install/lib/libnwc_simint.a || true
    ls -la  ${CACHEDIR}/simint.l5_p5_d1.install/lib/libsimint.a ||true
    bash -c "if [[ ! -z "${GITHUB_WORKSPACE}" ]]; then mkdir -p ${SINGULARITY_ROOTFS}/nwchem/contrib; rsync -a ${GITHUB_WORKSPACE}/nwchem/src ${SINGULARITY_ROOTFS}/nwchem/. ; rsync -a ${GITHUB_WORKSPACE}/nwchem/contrib/getmem.nwchem ${SINGULARITY_ROOTFS}/nwchem/contrib/. ;fi"
    bash -c "if [[  -f ${CACHEDIR}/ompi/lib/libmpi.so ]]; then mkdir -p ${SINGULARITY_ROOTFS}/opt ;rsync -a ${CACHEDIR}/ompi ${SINGULARITY_ROOTFS}/opt/. ; echo ompi/ucx cache fetched ;fi"
    bash -c "if [[  -f ${CACHEDIR}/libext/lib/libnwc_openblas.a ]]; then rsync -a ${CACHEDIR}/libext/* ${SINGULARITY_ROOTFS}/nwchem/src/libext/. ; echo libext cache fetched ;fi"
    bash -c "if [[  -f ${CACHEDIR}/simint.l5_p5_d1.install/lib/libsimint.a ]]; then rsync -av ${CACHEDIR}/simint.l5_p5_d1.install ${SINGULARITY_ROOTFS}/nwchem/src/NWints/simint/libsimint_source/. ; ln -sf ${SINGULARITY_ROOTFS}/nwchem/src/NWints/simint/libsimint_source/simint.l5_p5_d1.install  ${SINGULARITY_ROOTFS}/nwchem/src/NWints/simint/libsimint_source/simint_install;  ls -l ${SINGULARITY_ROOTFS}/nwchem/src/NWints/simint/libsimint_source/; echo simint cache fetched ;fi"
    echo '@@@ ls -l SINGULARITY_ROOTFS'
    ls -l ${SINGULARITY_ROOTFS}

##%files
##    ${GITHUB_WORKSPACE}/nwchem nwchem

%post
#
#https://sylabs.io/guides/3.6/user-guide/mpi.html
export DEBIAN_FRONTEND=noninteractive
export ompi=4.1.4
export ompi_prefix=ompi-$ompi
export ucx=1.12.1
export OMPI_DIR=/opt/ompi
export SINGULARITY_ompi=4.1.4
export SINGULARITY_ompi_prefix=ompi-$ompi
pwd \
&& apt-get -y update \
&& apt-get -y install -y tzdata git moreutils \
&& pwd \
&& echo '@@ ls -lart ' \
&& ls -lart  \
&& echo '@@ ls on /opt' \
&& ls -lart /opt \
&& bash -c "if [[ ! -f nwchem/src/GNUmakefile ]]; then git clone --depth 1  https://github.com/nwchemgit/nwchem.git; fi " \
&& apt-get -y install -y curl wget tar libnl-3-200 libnl-route-3-200 libgomp1 libnuma1 \
 g++ gfortran   make ssh patch curl  wget unzip perl-base file \
 python3 python3-dev cmake  unzip zip perl automake libtool autoconf flex  \
 libnuma-dev libslurm-dev libpmi2-0-dev libpmi0-dev  libnl-3-dev libnl-route-3-dev udev \
 librdmacm-dev librdmacm1 rdma-core libibverbs-dev  ibverbs-providers \
&& apt-get clean \
&& bash -c "if [[ ! -f /opt/ompi/lib/libmpi.so ]]; then  \
wget https://github.com/openucx/ucx/releases/download/v$ucx/ucx-$ucx.tar.gz \
&& tar xzf  ucx-$ucx.tar.gz \
&& cd ucx-$ucx \
&& mkdir build && cd build \
&& ../configure --prefix=$OMPI_DIR --disable-logging --disable-debug --disable-assertions --disable-params-check \
&& make -j4 && make install \
&& cd ../.. \
&& wget https://github.com/open-mpi/ompi/archive/v$ompi.tar.gz -O $ompi_prefix.tar.gz && \
tar xzf $ompi_prefix.tar.gz                                           && \
cd $ompi_prefix                                                        && \
./autogen.pl                                                           && \
./configure  --prefix=$OMPI_DIR --with-ucx=$OMPI_DIR --enable-mca-no-build=btl-uct   \
 --with-pmi --with-pmi-libdir=/usr/lib/x86_64-linux-gnu --enable-mpi1-compatibility --with-slurm --without-tm --without-lsf  \
 --without-sge --without-alps --without-lustre --disable-memchecker \
 --without-hcoll --disable-static  \
--disable-mpi-java --enable-dlopen --without-cuda --without-verbs \
--disable-mpi-cxx --disable-cxx-exceptions && \
echo 'UCX version from ompi/config.log' `grep 'UCX version' config.log`  && \
echo '************' && \
make -j 6                                                               && \
make install                                                            && \
make clean                                                              && \
#cd /tmp && \
#rm -rf /usr/share/doc/ && \
#rm -rf /usr/share/man/
cd ..  ; rm -rf *tar*gz $ompi-prefix ucx-$ucx ; fi "
echo ' check ucx' \
&& echo ' which ucx_info ' `which ucx_info|| true` \
&& echo ' ucx_info -v ' `ucx_info -v|| true` \
&& echo ' /opt/ompi/bin/ucx_info -v ' `/opt/ompi/bin/ucx_info -v|| true` \
&& echo '  ucx pkg ' `dpkg-query -l |grep  ucx  `  \
&& echo ' ucx Transports' `/opt/ompi/bin/ucx_info  -d |grep Transport |cut -c 19- || true` \
&& echo '********' 
export PATH=$OMPI_DIR/bin:$PATH
export LD_LIBRARY_PATH=$OMPI_DIR/lib:$LD_LIBRARY_PATH
export ARMCI_NETWORK=MPI-PR
#export NWCHEM_TOP=/opt/nwchem
export NWCHEM_TARGET=LINUX64
export NWCHEM_MODULES="all python gwmol"
#export NWCHEM_MODULES="nwdft driver solvation"
export BUILD_PLUMED=1
export USE_LIBXC=1
export BUILD_OPENBLAS=1
export BUILD_SCALAPACK=1
export BLAS_SIZE=8
export SCALAPACK_SIZE=8
#export USE_64TO32=y
export USE_MPI=y
export USE_MPIF=y
export USE_MPIF4=y
export USE_HWOPT=n
export USE_LIBXC=y
export USE_NOIO=y
export USE_SIMINT=y
export SIMINT_MAXAM=5
#ENV         MRCC_METHODS=y
#ENV         CCSDTQ=y
#ENV         CCSDTLR=y
ls -l nwchem* || true \
&& env|egrep BUILD_ \
&& bash -c "if [[ ! -f nwchem/src/GNUmakefile ]]; then git clone --depth 1  https://github.com/nwchemgit/nwchem.git; fi" \
&& cd nwchem \
&& export NWCHEM_TOP=`pwd` \
&& ls -lrt \
&& cd src \
&& ls -lrt libext/lib || true \
&& make nwchem_config && make -j6  \
&& ../contrib/getmem.nwchem 2000  || true \
&& make install INSTALL_PREFIX=/opt/nwchem \
&& DEBIAN_FRONTEND=noninteractive apt-get -y install localepurge \
&& echo MANDELETE >  /etc/locale.nopurge \
&& echo DONTBOTHERNEWLOCALE >> /etc/locale.nopurge \
&& echo en_US.UTF-8 >> /etc/locale.nopurge \
&& localepurge \
&& rm -rf /usr/share/doc  /usr/share/man \
&& du -sh /opt/nwchem \
&& du -sk /opt/nwchem/*|sort -n \
&& rm -rf tce tools nwdft NWints/simint/libsimint_source/simint.l?_p?_d? geom symmetry util nwxc ddscf lapack blas rism argos peigs rmdft gradients symmetry property smd lucia dplot propery hessian ccsd mp2_grad moints cafe analyz dimqm   develop libext/scalapack libext/openblas libext/libxc/libxc* libext/plumed* libext/libext_utils   ../lib || true\
&& ls -la NWints/simint/libsimint_source || true \
&& ls -la NWints/simint || true \
&& du -sk *|sort -n  || true\
&& cd .. \
&& du -sk *|sort -n || true \
&&  apt-get  -y purge cmake git  gcc-9  g++-9  gfortran-9  libstdc++-9-dev libgcc-9-dev \
&& apt-get -y install libgcc-s1  \
&& apt-get -y autoremove && apt-get clean \
&& dpkg-query -Wf '${Installed-Size}\t${Package}\n' | sort -n | tail -n 100


#clean unnecessary packages
#apt-get -y purge curl wget tar  cmake  unzip zip perl automake libtool autoconf flex  \
#&&  apt-get -y autoremove && apt-get clean

#cd /data
%environment
export ompi=4.1.4
export SINGULARITY_ompi=4.1.4
export SINGULARITY_ompi_prefix=ompi-$ompi
export OMPI_DIR=/opt/ompi
export SINGULARITY_OMPI_DIR=$OMPI_DIR
export SINGULARITYENV_APPEND_PATH=$OMPI_DIR/bin
export SINGULARITYENV_APPEND_LD_LIBRARY_PATH=$OMPI_DIR/lib

#export nwchem_hash=77ba3a6e1dd6f9ba26879d0416bb93b302f1f4f7
#export NWCHEM_TOP=/opt/nwchem
export FFIELD=amber
export AMBER_1=$NWCHEM_TOP/src/data/amber_s/
export AMBER_2=$NWCHEM_TOP/src/data/amber_q/
export AMBER_3=$NWCHEM_TOP/src/data/amber_x/
export AMBER_4=$NWCHEM_TOP/src/data/amber_u/
export SPCE=${NWCHEM_TOP}/src/data/solvents/spce.rst
export CHARMM_S=$NWCHEM_TOP/src/data/charmm_s/
export CHARMM_X=$NWCHEM_TOP/src/data/charmm_x/
export PATH=$PATH:/opt/nwchem/bin/
export PATH=$OMPI_DIR/bin:$PATH
export NWCHEM_BASIS_LIBRARY=/opt/nwchem/share/libraries/
export NWCHEM_NWPW_LIBRARY=/opt/nwchem/share/libraryps/
export LD_LIBRARY_PATH=$OMPI_DIR/lib:$LD_LIBRARY_PATH
#%runscript
#exec /bin/bash "$@"
