Bootstrap: docker
From: genomicpariscentre/guppy-gpu:6.0.0

%labels
    MAINTAINER icaoberg
    EMAIL icaoberg@psc.edu
    SUPPORT help@psc.edu
    REPOSITORY http://gitub.com/pscedu/singularity-guppy
    COPYRIGHT Copyright © 2022 Pittsburgh Supercomputing Center. All Rights Reserved.    
    VERSION 6.0.0


