#!/bin/bash
#
# Christophe Demay <christophe.demay@chru-lille.fr>
# 2018/11/06: initial version


Bootstrap: docker
From: brentp/slivar:v0.2.7

%labels
  MAINTAINER christophe.demay@chru-lille.fr
  VERSION 1.15.1


%post


