BootStrap: docker
From: ubuntu:20.04

%apprun kallisto
  exec kallisto "${@}"

%post
  KALLISTO_VER=0.46.1 && \
  # XXX: To avoid interactive dialogue
  export DEBIAN_FRONTEND=noninteractive && \
  ln -snf /usr/share/zoneinfo/UTC /etc/localtime && echo UTC > /etc/timezone && \
  apt-get update && \
  apt-get install -y \
    build-essential \
    cmake \
    make \
    zlib1g-dev \
    autoconf \
    libhdf5-dev \
    git \
    python \
    python3-pip && \
  mkdir src && \
  cd src && \
  git clone https://github.com/pachterlab/kallisto.git -b v${KALLISTO_VER} && \
  cd kallisto/ext/htslib && \
  autoheader && \
  autoconf && \
  cd ../.. && \
  mkdir build && \
  cd build && \
  cmake .. && \
  make && \
  make install && \
  cd && rm -rf src
