Bootstrap: docker
From: ubuntu:18.04

%post
    apt-get update && apt-get install -y --no-install-recommends \
        curl ca-certificates \
        libglib2.0-dev libx11-dev libx11-xcb-dev libxcomposite-dev libxcursor-dev \
        libnss3 libdbus-1-dev libgdk-pixbuf2.0-dev libgtk-3-dev libxss-dev libasound-dev

    cd /opt
    curl -sL https://deb.nodesource.com/setup_12.x | bash -
    apt-get install -y nodejs

    npm install electron -g --allow-root --unsafe-perm=true

    export ELECTRON_HOME=/usr/lib/node_modules/electron/dist
    chmod 4755 $ELECTRON_HOME/chrome-sandbox

    rm -rf /var/lib/apt/lists/*

%runscript
    exec electron --no-sandbox $@

%help
Electron 8.2.5
Node.js 12

%environment
    export ELECTRON_HOME=/usr/lib/node_modules/electron/dist
    export LD_LIBRARY_PATH=${ELECTRON_HOME}:$LD_LIBRARY_PATH
    export LC_ALL=C

%labels
AUTHOR rs7wz@virginia.edu
