Bootstrap: docker
From: continuumio/miniconda3

# sudo singularity build chip-seq-pipeline.simg Singularity

%files
	project.scif
	Snakefile
	config.yaml

%environment
	PATH=/opt/conda/bin:$PATH
	export PATH

%post
	apt-get -y update
	apt-get -y install build-essential libboost-all-dev libgsl-dev libz-dev git

	# Set up Conda channels
	conda config --add channels r
	conda config --add channels conda-forge
	conda config --add channels bioconda

	# Install scif and scif-apps
	/opt/conda/bin/pip install scif
	/opt/conda/bin/scif install /project.scif

	# Install snakemake
	/opt/conda/bin/conda install --yes snakemake=4.8.1
	/opt/conda/bin/conda install --yes docutils=0.14

%runscript
	exec scif "$@"
