Bootstrap: docker
From: quay.io/biocontainers/kraken2:2.1.2--pl5262h7d875b9_0

%labels
    AUTHOR icaoberg
    EMAIL icaoberg@psc.edu
    WEBSITE http://gitub.com/pscedu/singularity-kraken2
    COPYRIGHT Copyright © 2021 Pittsburgh Supercomputing Center. All Rights Reserved.    
    VERSION 2.1.2
