Bootstrap: docker
From: nextgenusfs/funannotate:v1.8.9

%labels
    MAINTAINER icaoberg
    EMAIL icaoberg@psc.edu
    SUPPORT help@psc.edu
    REPOSITORY https://github.com/pscedu/singularity-funannotate
    COPYRIGHT Copyright © 2022 Pittsburgh Supercomputing Center. All Rights Reserved.
    VERSION 1.8.9
