Bootstrap: docker
From: continuumio/anaconda3

%labels
    MAINTAINER icaoberg
    EMAIL icaoberg@psc.edu
    SUPPORT help@psc.edu
    REPOSITORY https://github.com/pscedu/singularity-funannotate
    COPYRIGHT Copyright © 2022 Pittsburgh Supercomputing Center. All Rights Reserved.
    VERSION 1.8.9

%post
    apt update
    conda config --add channels defaults
    conda config --add channels bioconda
    conda config --add channels conda-forge
    conda create -n funannotate "python>=3.6,<3.9" funannotate=1.8.9
