#!/bin/bash
#
# Chadi Saad <chadi.saad@chru-lille.fr>
# 2018/11/06: initial version


BootStrap: docker
From: phusion/baseimage:0.11

%labels
  MAINTAINER chadi.saad@chru-lille.fr

%environment
  export  LC_ALL=en_US.UTF-8
  export  LANGUAGE=en_US.UTF-8
  export  PATH="/miniconda/bin/:${PATH}"
%help


%post
	echo 'debconf debconf/frontend select Noninteractive' | debconf-set-selections
  apt-get clean 

  apt-get update
  apt-get -y install build-essential \
  wget 


wget https://repo.continuum.io/miniconda/Miniconda2-4.7.12.1-Linux-x86_64.sh 

bash Miniconda2-4.7.12.1-Linux-x86_64.sh -p /miniconda -b
rm   Miniconda2-4.7.12.1-Linux-x86_64.sh

/miniconda/bin/conda config --add channels defaults
/miniconda/bin/conda config --add channels bioconda
/miniconda/bin/conda config --add channels conda-forge
/miniconda/bin/conda config --set ssl_verify no
/miniconda/bin/conda config --set default_threads 12


/miniconda/bin/conda install -c bioconda cnvkit=0.9.6



      
