BootStrap: localimage
From: ../../singularity-rstudio/rstudio_2022072.576-r421tv132.sif

%post
  apt-get update && \
  apt-get install -y less

# Install methyl-seq packages
%post
  R -e 'install.packages("BiocManager")' && \
  R -e 'BiocManager::install(version = "3.15")' && \
  R -e 'BiocManager::install("AnnotationDbi")' && \
  R -e 'BiocManager::install("org.Hs.eg.db")' && \
  R -e 'BiocManager::install("org.Mm.eg.db")' && \
  R -e 'BiocManager::install("clusterProfiler")' && \
  R -e 'BiocManager::install("genomation")' && \
  R -e 'BiocManager::install("GenomicRanges")' && \
  R -e 'BiocManager::install("GO.db")' && \
  R -e 'BiocManager::install("methylKit")' && \
  R -e 'BiocManager::install("rtracklayer")'
