Bootstrap:docker
From:nfcore/base

%labels
	MAINTAINER Viktor henmyr <viktor.henmyr@skane.se>
	DESCRIPTION Singularity container for solid-tumour ffpe pipeline
	VERSION 0.0.1

%environment
	PATH=/opt/conda/envs/somatic_general/bin:/opt/sentieon-genomics-201808.05/bin/:/opt/bin:/opt/conda/envs/peddy/bin:$PATH
	PICARD_HOME=/opt/conda/envs/somatic_general/share/picard-2.18.26-0/
	export PERL5LIB=$PERL5LIB:/opt/conda/envs/somatic_general/lib/site_perl/5.26.2/
	export PERL5LIB=$PERL5LIB:/opt/conda/envs/somatic_general/lib/site_perl/5.26.2/x86_64-linux-thread-multi/
	export PERL5LIB=$PERL5LIB:/opt/bin/

%files
    resources/somatic_conda.yml /
	/data/bnf/sw/sentieon/sentieon-genomics-201808.05 /opt

%post
	/opt/conda/bin/conda env create -f /somatic_conda.yml
	apt -y install libz-dev build-essential gettext cmake libxml2-dev libcurl4-openssl-dev libssl-dev make
	/opt/conda/envs/somatic_general/bin/cpanm Path::Tiny --force
	/opt/conda/envs/somatic_general/bin/cpanm MongoDB::Collection
	/opt/conda/bin/conda clean -a