#!/bin/bash
#
# Chadi Saad <chadi.saad@chru-lille.fr>
# 2018/11/06: initial version


BootStrap: docker
From: phusion/baseimage:0.11

%labels
  MAINTAINER chadi.saad@chru-lille.fr

%environment
  export  LC_ALL=en_US.UTF-8
  export  LANGUAGE=en_US.UTF-8
  export  PATH="/miniconda/bin/:${PATH}"

%help


%post
	echo 'debconf debconf/frontend select Noninteractive' | debconf-set-selections
  apt-get clean 

  apt-get update
  apt-get -y install build-essential \
  wget 


export  PATH="/miniconda/bin/:${PATH}"

## install miniconda
wget https://repo.continuum.io/miniconda/Miniconda3-4.5.12-Linux-x86_64.sh 

bash Miniconda3-4.5.12-Linux-x86_64.sh -p /miniconda -b
rm   Miniconda3-4.5.12-Linux-x86_64.sh



conda config --add channels defaults


conda install  -c bioconda  spliceai=1.3

