#!/bin/bash
#
# Christophe Demay <christophe.demay@chru-lille.fr>
# 2019/03/11: initial version


Bootstrap: docker
From: broadinstitute/gatk:4.1.0.0

%labels
  MAINTAINER christophe.demay@chru-lille.fr
  VERSION 4.1.0.0

%environment

%help

%post