Bootstrap: docker
From: ubuntu:18.04

%setup
     ## The "%setup"-part of this script is called to bootstrap an empty
     ## container. It copies the source files from the branch of your
     ## repository where this file is located into the container to the
     ## directory "/planner". Do not change this part unless you know
     ## what you are doing and you are certain that you have to do so.

    REPO_ROOT=`dirname $SINGULARITY_BUILDDEF`
    cp -r $REPO_ROOT/ $SINGULARITY_ROOTFS/planner

%post

    ## The "%post"-part of this script is called after the container has
    ## been created with the "%setup"-part above and runs "inside the
    ## container". Most importantly, it is used to install dependencies
    ## and build the planner. Add all commands that have to be executed
    ## once before the planner runs in this part of the script.

    ## Install all necessary dependencies.
    apt-get update
    apt-get -y install cmake gawk g++ g++-multilib make python python-dev python-pip ca-certificates
    pip install mock==2.0.0 h5py==2.7.1 keras==2.1.6 numpy==1.14.3 pillow==5.1.0 scipy==1.0.1 tensorflow==1.8.0 subprocess32==3.2.7

    ## Build your planner
    cd /planner
    ./build.py release64 -j4
    cd /planner/symba
    ./build -j4

    ## Strip binaries.
    strip --strip-all /planner/builds/release64/bin/downward \
        /planner/builds/release64/bin/preprocess \
        /planner/symba/src/preprocess/preprocess \
        /planner/symba/src/search/downward-1 \
        /planner/symba/src/search/downward-2 \
        /planner/symba/src/search/downward-4

    ## Remove packages unneeded for running the planner.
    apt-get -y autoremove cmake g++ make
    rm -rf /var/lib/apt/lists/*

    ## Only keep essential binaries.
    ## Symba.
    mkdir -p /compiled-planner/symba/src/preprocess
    mkdir -p /compiled-planner/symba/src/search
    mv /planner/symba.py /compiled-planner
    mv /planner/symba/src/plan-ipc /planner/symba/src/plan /planner/symba/src/translate /compiled-planner/symba/src
    mv /planner/symba/src/preprocess/preprocess /compiled-planner/symba/src/preprocess
    mv /planner/symba/src/search/dispatch /planner/symba/src/search/unitcost /planner/symba/src/search/downward /planner/symba/src/search/downward-1 /planner/symba/src/search/downward-2 /planner/symba/src/search/downward-4 /planner/symba/src/search/cudd-2.5.0 /compiled-planner/symba/src/search

    ## Rest.
    mkdir -p /compiled-planner/builds/release64
    mv /planner/driver /compiled-planner
    mv /planner/fast-downward.py /planner/plan-ipc.py /planner/create-image-from-graph.py /planner/timers.py /compiled-planner
    mv /planner/dl_model /compiled-planner
    rm -rf /compiled-planner/dl_model/model_creation /compiled-planner/dl_model/model.h5 /compiled-planner/dl_model/model.json
    mv /planner/builds/release64/bin /compiled-planner/builds/release64
    mkdir -p /compiled-planner/src
    mv /planner/src/translate/ /compiled-planner/src/
    rm -rf /third-party
    rm -rf /planner
    mv /compiled-planner /planner

%runscript
    ## The runscript is called whenever the container is used to solve
    ## an instance.

    DOMAINFILE=$1
    PROBLEMFILE=$2
    PLANFILE=$3

    ## Call your planner.
    /planner/plan-ipc.py \
        $DOMAINFILE \
        $PROBLEMFILE \
        $PLANFILE \
        --image-from-lifted-task

## Update the following fields with meta data about your submission.
## Please use the same field names and use only one line for each value.
%labels
Name        Delfi1
Description This planner uses an offline learned algorithm selector to choose the "best" planner online based on a abstract structure graph of the PDDL description of the planning task. In particular, the learning algorithm uses such graphs of a planning task, turns them into an image and uses the planner runtime to train a neural net. The learned model thus predicts runtime of planners on a given task and chooses a planner accordingly.
Authors     Michael Katz <michael.katz1@ibm.com>, Shirin Sohrabi <ssohrab@us.ibm.com>, Horst Samulowitz <samulowitz@us.ibm.com>, and Silvan Sievers <silvan.sievers@unibas.ch>
SupportsDerivedPredicates no
SupportsQuantifiedPreconditions no
SupportsQuantifiedEffects no
