Bootstrap: docker
From: continuumio/miniconda3:latest
Stage: condabuild
%files
environments/environment.yml /environment.yml
environments/extras.yml /extras.yml
%labels
authors="Muhammad Zohaib Anwar, Ivan Gill, Madeline Iseminger, Anoosha Sehar & William Hsiao"
description="Singularity Container image containing all requirements for the nf-ncov-voc"
%post

/opt/conda/bin/conda env create -f /environment.yml
/opt/conda/bin/conda env create -f /extras.yml
PATH=/opt/conda/envs/nf-ncov-voc/bin:$PATH
PATH=/opt/conda/envs/nf-ncov-voc-extra/bin:$PATH

%environment
export PATH=/opt/conda/envs/nf-ncov-voc/bin:$PATH
export PATH=/opt/conda/envs/nf-ncov-voc-extra/bin:$PATH
