Bootstrap: docker
From: quay.io/biocontainers/phylip:3.697--h470a237_0

%labels
    AUTHOR icaoberg
    EMAIL icaoberg@psc.edu
    WEBSITE https://github.com/icaoberg/singularity-phylip-suite
    COPYRIGHT Copyright © 2021 Pittsburgh Supercomputing Center. All Rights Reserved. 
    VERSION 3.697

%post
   rm /etc/resolv.conf

####################################################################################
