Bootstrap: docker
From: quay.io/biocontainers/phylip:3.697--h470a237_0

%labels
    MAINTAINER icaoberg
    EMAIL icaoberg@psc.edu
    WEBSITE https://github.com/pscedu/singularity-phylip-suite
    COPYRIGHT Copyright © 2021 Pittsburgh Supercomputing Center. All Rights Reserved. 
    VERSION 3.697
