Bootstrap: docker
From: python:3.8-alpine

%labels
    AUTHOR icaoberg
    EMAIL icaoberg@psc.edu
    SUPPORT help@psc.edu
    REPOSITORY http://gitub.com/pscedu/singularity-visidata
    COPYRIGHT Copyright © 2021-2023 Pittsburgh Supercomputing Center. All Rights Reserved.
    VERSION 2.11.1

%environment
    export TERM="xterm-256color"

%post
    apk update
    apk add git man-pages mandoc
    pip install requests python-dateutil wcwidth tabulate
    mkdir -p /opt/visidata
    git clone https://github.com/saulpw/visidata.git
    cd visidata
    git checkout tags/v2.11.1
    sh -c 'yes | pip install -vvv .'
    rm -rfv visidata
    pip install --upgrade pip
    pip install xlrd openpyxl
