Bootstrap: shub
From: mkandes/ubuntu:latest

%labels

    APPLICATION_NAME ubuntu + openmpi
    APPLICATION_VERSION 18.04 + 3.1.4
    APPLICATION_URL https://www.open-mpi.org

    SINGULARITY_VERSION 2.6.1
    SINGULARITY_IMAGE_SIZE 2048

    AUTHOR_NAME Marty Kandes
    AUTHOR_EMAIL mkandes@sdsc.edu

    LAST_UPDATED 20200408

%setup

%environment

    # Set paths to OpenMPI binaries and libraries
    export PATH="/opt/openmpi-3.1.4/bin:${PATH}"
    export LD_LIBRARY_PATH="/opt/openmpi-3.1.4/lib:${LD_LIBRARY_PATH}"

    # Set paths to OSU Microbenchmarks binaries
    export PATH="/opt/omb-5.6.2/collective:${PATH}"
    export PATH="/opt/omb-5.6.2/one-sided:${PATH}"
    export PATH="/opt/omb-5.6.2/pt2pt:${PATH}"
    export PATH="/opt/omb-5.6.2/startup:${PATH}"

%post -c /bin/bash

    # Set operating system mirror URL
    export MIRRORURL='http://us.archive.ubuntu.com/ubuntu'

    # Set operating system version
    export OSVERSION='bionic'

    # Set system locale
    export LC_ALL='C'

    # Set debian frontend interface
    export DEBIAN_FRONTEND='noninteractive'

    # Set path to miniconda
    export PATH="/opt/miniconda3/bin:${PATH}"

    # Upgrade all packages to their latest versions
    apt-get -y update && apt-get -y upgrade

    # Install basic drivers for user space access to Ethernet, RDMA,
    # and Infiniband. See https://community.mellanox.com/docs/DOC-2431
    apt-get -y install dkms
    apt-get -y install infiniband-diags
    apt-get -y install libibverbs-dev
    apt-get -y install ibacm
    apt-get -y install librdmacm-dev
    #apt-get -y install libmlx4-dev
    #apt-get -y install libmlx5-dev
    apt-get -y install mstflint
    #apt-get -y install libibcm-dev
    apt-get -y install libibmad-dev
    apt-get -y install libibumad-dev
    apt-get -y install opensm
    apt-get -y install srptools

    # Install additional tools
    apt-get -y install ibutils
    apt-get -y install ibverbs-utils
    apt-get -y install rdmacm-utils
    apt-get -y install perftest
    apt-get -y install numactl
    apt-get -y install libnuma-dev

    # Install libnl
    apt-get -y install libnl-3-200
    apt-get -y install libnl-route-3-200
    apt-get -y install libnl-route-3-dev
    apt-get -y install libnl-utils

    # Install OpenMPI dependencies
    apt-get -y install zlib1g-dev

    cd /tmp

    # Download, build, and install OpenMPI
    wget https://download.open-mpi.org/release/open-mpi/v3.1/openmpi-3.1.4.tar.gz
    tar -xf openmpi-3.1.4.tar.gz
    cd openmpi-3.1.4
    ./configure --prefix=/opt/openmpi-3.1.4
    make all install

    # Set paths to OpenMPI binaries and libraries
    export PATH="/opt/openmpi-3.1.4/bin:${PATH}"
    export LD_LIBRARY_PATH="/opt/openmpi-3.1.4/lib:${LD_LIBRARY_PATH}"

    cd /tmp

    # Download, build, and install OSU Microbenchmarks
    wget http://mvapich.cse.ohio-state.edu/download/mvapich/osu-micro-benchmarks-5.6.2.tar.gz
    tar -xzvf osu-micro-benchmarks-5.6.2.tar.gz
    cd osu-micro-benchmarks-5.6.2
    ./configure --prefix='/opt/omb-5.6.2' CC='mpicc' CXX='mpicxx'
    make
    make install

    # Reorganize OSU Microbenchmarks directory structure
    cd /opt/omb-5.6.2
    mv libexec/osu-micro-benchmarks/mpi/collective ./
    mv libexec/osu-micro-benchmarks/mpi/one-sided ./
    mv libexec/osu-micro-benchmarks/mpi/pt2pt ./
    mv libexec/osu-micro-benchmarks/mpi/startup ./
    rm -rf libexec

    # Cleanup
    apt-get -y autoremove --purge
    apt-get -y clean

    # Update database for mlocate
    updatedb

%files

%runscript

%test
