Bootstrap:docker
From:nfcore/base

%labels
	MAINTAINER Per Brattås <per.brattas@med.lu.se>
	DESCRIPTION Singularity container Cellranger-ATAC
	VERSION 0.0.1

%environment
	PATH=/opt/cellranger-atac-1.2.0:/opt/bin:$PATH

%setup
	cp -R /data/bnf/sw/cellranger-atac-1.2.0 ${SINGULARITY_ROOTFS}/opt
	cp -R /data/bnf/sw/fastqc/FastQC_0.11.5 ${SINGULARITY_ROOTFS}/opt
	cp --preserve=timestamp -R /data/bnf/ref/cellranger/refdata-cellranger-atac-GRCh38-1.2.0 ${SINGULARITY_ROOTFS}/opt
	cp --preserve=timestamp -R /data/bnf/ref/cellranger/refdata-cellranger-atac-mm10-1.2.0	${SINGULARITY_ROOTFS}/opt
	
%files
	/data/bnf/sw/bcl2fastq2-v2.20.0.422-Source.tar.gz /opt   

%post
	rm -rf /var/lib/apt/lists/*
	apt -y clean
	apt -y update
	apt -y install libz-dev build-essential gettext cmake libxml2-dev libcurl4-openssl-dev libssl-dev make libbz2-dev libboost-dev python3-pip sudo

	mkdir -p /usr/share/man/man1
	
	sudo apt -y install default-jre

	# Setup multiqc
	pip3 install multiqc

	# Setup bcl2fastq
	export TMP=/tmp
	export SOURCE=/tmp${TMP}/bcl2fastq
	export BUILD=${TMP}/bcl2fastq2-v2.20.0-build
	export INSTALL_DIR=${SINGULARITY_ROOTFS}/opt/bcl2fastq2-v2.20.0

	mkdir /opt/bin
        mkdir /opt/bcl2fastq
        cd /opt/bcl2fastq
        mkdir build

	export C_INCLUDE_PATH=/usr/include/x86_64-linux-gnu

	tar -xzvf /opt/bcl2fastq2-v2.20.0.422-Source.tar.gz
        chmod ugo+x bcl2fastq/src/configure
        chmod ugo+x bcl2fastq/src/cmake/bootstrap/installCmake.sh
        cd build
        ../bcl2fastq/src/configure --prefix=/opt/
        make
        make install

	# Link fastqc 
	ln -s /opt/FastQC_0.11.5/fastqc /opt/bin/fastqc

	