Bootstrap: docker
From: meren/anvio:7

%labels
    MAINTAINER icaoberg
    EMAIL icaoberg@psc.edu
    SUPPORT help@psc.edu
    REPOSITORY https://github.com/pscedu/singularity-anvio
    COPYRIGHT Copyright © 2022-2023 Pittsburgh Supercomputing Center. All Rights Reserved.
    VERSION 7
