Bootstrap: docker
From: nvidia/cuda:8.0-cudnn5-devel-ubuntu16.04

%setup
	#Runs on host
	#The path to the image is $SINGULARITY_ROOTFS

%post

	#Default mount paths
	mkdir /scratch /data /shared /fastdata


	#Add nvidia driver paths
	echo "\n #Nvidia driver paths \n" >> /environment
	echo 'export PATH="/nvbin:$PATH"' >> /environment
	echo 'export LD_LIBRARY_PATH="/nvlib:$LD_LIBRARY_PATH"' >> /environment


	#Add CUDA paths
	echo "\n #Cuda paths \n" >> /environment
	echo 'export CPATH="/usr/local/cuda/include:$CPATH"' >> /environment
	echo 'export PATH="/usr/local/cuda/bin:$PATH"' >> /environment
	echo 'export LD_LIBRARY_PATH="/usr/local/cuda/lib64:$LD_LIBRARY_PATH"' >> /environment
	echo 'export CUDA_HOME="/usr/local/cuda"' >> /environment


%runscript
	#Executes with the singularity run command
	#delete this section to use existing docker ENTRYPOINT command



%test
