Bootstrap: yum 
OSVersion: 7
MirrorURL: http://mirror.centos.org/centos-7/7/os/x86_64
Include: yum

%labels

    APPLICATION_NAME centos
    APPLICATION_VERSION 7.7.1908
    APPLICATION_URL https://www.centos.org

    SINGULARITY_VERSION 2.6.1
    SINGULARITY_IMAGE_SIZE 4096

    AUTHOR_NAME Marty Kandes
    AUTHOR_EMAIL mkandes@sdsc.edu

    LAST_UPDATED 20200407

%setup

%environment

    # Set operating system mirror URL
    export MIRRORURL='http://mirror.centos.org/centos-7/7/os/x86_64'

    # Set operating system version
    export OSVERSION='7'

    # Set system locale
    export LC_ALL=C

    # Set path to miniconda
    #export PATH="/opt/miniconda3/bin:${PATH}"

%post -c /bin/bash

    # Set operating system mirror URL
    export MIRRORURL='http://mirror.centos.org/centos-7/7/os/x86_64'

    # Set operating system version
    export OSVERSION='7'

    # Set system locale
    export LC_ALL=C

    # Add software repositories
    yum -y install epel-release

    # Install system software metapackages
    yum -y groupinstall "Development Tools"
    yum -y groupinstall "Additional Development"
    yum -y groupinstall "Compatibility Libraries"

    # Update all software packages to their latest versions
    yum -y check-update && yum -y update

    # Install common software packages
    yum -y install bc
    yum -y install cmake
    yum -y install curl
    yum -y install mlocate
    yum -y install python3
    yum -y install rsync
    yum -y install time
    yum -y install wget
    yum -y install which
    yum -y install yum-utils

    # Install expect to answer responses to interactive build questions
    yum -y install expect

    # Use /tmp to store temporary files within the container during the
    # bootstraping process
    cd /tmp

    # Install miniconda3
    #wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
    #chmod +x Miniconda3-latest-Linux-x86_64.sh
    #./Miniconda3-latest-Linux-x86_64.sh -b -p /opt/miniconda3

    # Cleanup
    package-cleanup -q --leaves | xargs -l1 yum -y remove
    yum -y clean all

    # Update database for mlocate
    updatedb

%files

%runscript

%test
