Bootstrap: docker
From: conda/miniconda3
Stage: devel

%files
environment.yml /environment.yml

 
%post

apt-get update && apt-get install -y  procps 
conda update -n base -c defaults conda
conda env create -n environment -f /environment.yml
conda install -c conda-forge conda-pack
conda-pack -n environment -o /tmp/env.tar && mkdir /venv && cd /venv && tar xf /tmp/env.tar && rm /tmp/env.tar
/venv/bin/conda-unpack
chmod +x /venv/bin/*



Bootstrap: docker
From: debian:buster-slim 
Stage: final
IncludeCmd: yes

%files from devel
/venv /venv

%files
debian.packages.run.list /opt/packages.run.list
SOFTWARE.tsv /opt

%post
apt update && apt install -y $(cat /opt/packages.run.list)
apt clean

mkdir -p /opt/wrappers
echo "#!/bin/bash\ncat /opt/SOFTWARE.tsv\n" > /opt/wrappers/software_info
chmod +x /opt/wrappers/software_info

%environment
export PATH=/venv/bin:/opt/wrappers:$PATH

%runscript
"$@"

%test
echo "[Test] snpeff help"
snpEff -version

%labels
    Maintainer Sebastien.Carrere@inrae.fr
    Version 5.1

%help
## SNPEFF

SnpEff is a variant annotation and effect prediction tool. It annotates and predicts the effects of genetic variants (such as amino acid changes).

### USAGE

	$ {IMAGE} snpEff
	$ {IMAGE} tabix

### CITATION

A program for annotating and predicting the effects of single nucleotide polymorphisms, SnpEff: SNPs in the genome of Drosophila melanogaster strain w1118; iso-2; iso-3.", Cingolani P, Platts A, Wang le L, Coon M, Nguyen T, Wang L, Land SJ, Lu X, Ruden DM. Fly (Austin). 2012 Apr-Jun;6(2):80-92. PMID: 22728672


