BootStrap: docker
From: alpine:latest

%labels
  Maintainer Christian Dietrich
  TrimGalore_Version 0.5.0

%apprun trim_galore
  exec trim_galore "${@}"

%runscript
  exec trim_galore "${@}"

%post
  # Install OpenJRE 8 (headless)
  echo "http://mirror.leaseweb.com/alpine/v3.8/community" >> /etc/apk/repositories
  apk update
  apk add openjdk8-jre-base perl python3 python3-dev gcc g++

  # Install FastQC
  mkdir /opt
  wget -O - https://www.bioinformatics.babraham.ac.uk/projects/fastqc/fastqc_v0.11.8.zip | unzip -qod /opt/ -
  ln -s /opt/FastQC/fastqc /usr/local/bin/fastqc
  chmod +x /usr/local/bin/fastqc

  # Install Cutadapt
  pip3 --no-cache-dir install cutadapt==1.18

  # Install TrimGalore
  wget -O - https://github.com/FelixKrueger/TrimGalore/archive/0.5.0.tar.gz | tar zxf - -C /opt
  ln -s /opt/TrimGalore-*/trim_galore /usr/local/bin/trim_galore

  # Clean up
  apk del python3-dev g++ gcc
  rm -rf /var/cache/apk/*
