Bootstrap: docker
From: quay.io/biocontainers/bowtie2:2.4.4--py39hbb4e92a_0

%labels
    AUTHOR icaoberg
    EMAIL icaoberg@psc.edu
    SUPPORT help@psc.edu
    REPOSITORY https://github.com/pscedu/singularity-bowtie2
    COPYRIGHT Copyright © 2021 Pittsburgh Supercomputing Center. All Rights Reserved. 
    VERSION 2.4.4
