BootStrap: docker
From: alpine:latest

%labels
  Maintainer Christian Dietrich
  SAMtools_Version 1.9

%apprun samtools
  exec samtools "${@}"

%runscript
  exec samtools "${@}"

%post
  # Get dependencies
  apk update
  apk add make gcc g++ ncurses-dev ncurses-libs zlib-dev zlib bzip2-dev libbz2 xz-dev xz-libs curl-dev libcurl

  # Install SAMtools
  cd /tmp
  wget https://github.com/samtools/samtools/releases/download/1.9/samtools-1.9.tar.bz2
  tar xjf samtools-1.9.tar.bz2
  cd samtools-*
  make -j$(nproc) install

  # Clean up
  apk del gcc make g++ ncurses-dev zlib-dev bzip2-dev xz-dev curl-dev
  rm -rf /var/cache/apk/*
  rm -rf /tmp/*
