Bootstrap: docker
From: alpine:edge

%labels
    MAINTAINER icaoberg
    EMAIL icaoberg@psc.edu
    REPOSITORY https://github.com/pscedu/singularity-lazygit
    COPYRIGHT Copyright © 2021 Pittsburgh Supercomputing Center. All Rights Reserved.
    VERSION 0.22.9

%post
    apk update
    apk add lazygit=0.22.9 git

####################################################################################
%apphelp lazygit
    lazygit --help

%apprun lazygit
    lazygit "$@"
