Bootstrap: docker
From: quay.io/biocontainers/bcftools:1.10.2--h4f4756c_2

%labels
    AUTHOR icaoberg
    EMAIL icaoberg@psc.edu
    WEBSITE http://github.com/pscedu/singularity-bcftools
    COPYRIGHT Copyright © 2021 Pittsburgh Supercomputing Center. All Rights Reserved. 
    VERSION 1.10.2



####################################################################################
