Bootstrap: docker
From: alpine:edge

%labels
    AUTHOR icaoberg
    EMAIL icaoberg@psc.edu
    WEBSITE http://github.com/icaoberg/singularity-term-img-cli
    COPYRIGHT Copyright © 2021 Pittsburgh Supercomputing Center. All Rights Reserved. 
    VERSION 4.1.0

%post
    apk add --update nodejs npm
    npm install --global term-img-cli

####################################################################################
