Bootstrap: docker
From: nvidia/cuda:9.0-cudnn7-devel-ubuntu16.04

%environment

	#Environment variables

	#Add CUDA paths
	CPATH="/usr/local/cuda/include:$CPATH"
	PATH="/usr/local/cuda/bin:$PATH"
	LD_LIBRARY_PATH="/usr/local/cuda/lib64:$LD_LIBRARY_PATH"
	CUDA_HOME="/usr/local/cuda"

	#Add Anaconda path
	PATH="/usr/local/anaconda3-4.2.0/bin:$PATH"

	#Add MKL preload
	LD_PRELOAD=/usr/local/anaconda3-4.2.0/lib/libmkl_core.so:/usr/local/anaconda3-4.2.0/lib/libmkl_sequential.so:/usr/local/anaconda3-4.2.0/lib/libmkl_avx2.so:/usr/local/anaconda3-4.2.0/lib/libmkl_def.so
	
	export PATH LD_LIBRARY_PATH CPATH CUDA_HOME LD_PRELOAD


%setup
	#Runs on host
	#The path to the image is $SINGULARITY_ROOTFS



%post
	#Post setup script

	#Add Anaconda path
	PATH="/usr/local/anaconda3-4.2.0/bin:$PATH"
	export PATH


	#Default mount paths
	mkdir /scratch /data /shared /fastdata


	#Updating and getting required packages
	apt-get update
	apt-get install -y wget git vim

	
	cd /tmp

	#Download and install Anaconda
	CONDA_INSTALL_PATH="/usr/local/anaconda3-4.2.0"
	wget https://repo.continuum.io/archive/Anaconda3-4.2.0-Linux-x86_64.sh
	chmod +x Anaconda3-4.2.0-Linux-x86_64.sh
	./Anaconda3-4.2.0-Linux-x86_64.sh -b -p $CONDA_INSTALL_PATH

	pip install -U pip

	#Install Tensorflow
	pip install tensorflow-gpu

	#Install Keras
	pip install  keras

	conda update -y scikit-learn


%runscript
	#Executes with the singularity run command
	#delete this section to use existing docker ENTRYPOINT command


%test
	#Test that script is a success

	#Add Anaconda path
	PATH="/usr/local/anaconda3-4.2.0/bin:$PATH"
	export PATH

	#Test tensorflow install (can't test as it requires GPU)
	#python -c "import tensorflow"
