Bootstrap: docker
From: conda/miniconda3
Stage: devel

%files
environment.yml /environment.yml

 
%post

apt-get update && apt-get install -y  procps 
conda update -n base -c defaults conda
conda env create -n bedtools -f /environment.yml
conda install -c conda-forge conda-pack
conda-pack -n bedtools -o /tmp/env.tar && mkdir /venv && cd /venv && tar xf /tmp/env.tar && rm /tmp/env.tar
/venv/bin/conda-unpack
chmod +x /venv/bin/*



Bootstrap: docker
From: debian:buster-slim 
Stage: final
IncludeCmd: yes

%files from devel
/venv /venv

%files
debian.packages.run.list /opt/packages.run.list
debian.packages.build.list /opt/packages.build.list
wrappers /opt
SOFTWARE.tsv /opt/

%post
apt update && apt install -y $(cat /opt/packages.build.list) $(cat /opt/packages.run.list)
#install lipmutils corelib
mkdir -p /opt/lipmutils
cd /opt/lipmutils
mv /opt/wrappers/corelib.tgz . && tar xfz corelib.tgz

#clean
apt remove -y $(cat /opt/packages.build.list) && apt autoremove -y
apt clean
apt purge

echo "#!/bin/bash\ncat /opt/SOFTWARE.tsv\n" > /opt/wrappers/software_info
chmod +x /opt/wrappers/software_info


%environment
export LC_ALL=C
export PERL5LIB=$PERL5LIB:/opt/lipmutils/corelib:/opt/wrappers/lib
export PATH=/opt/wrappers:/venv/bin:$PATH

%runscript
"$@"

%test
echo "[Test] bedtools help"
bedtools --version

%labels
    Maintainer Sebastien.Carrere@inrae.fr
    Version bedtools-2.30.0,lipmutils-1.0

%help
## LIPMUTILS SCRIPTS

A set of script written by LIPME Bioinformatics Team

### USAGE

	$ {IMAGE} bedtools --help
	$ {IMAGE} lipm_bed_filter.pl --help
	$ {IMAGE} lipm_bed_split_by_sequence.pl --help
	$ {IMAGE} lipm_bed_to_expr.pl --help
	$ {IMAGE} lipm_bed_to_gff3.pl --help
	$ {IMAGE} lipm_fasta2overlappingwins.pl --help
	$ {IMAGE} lipm_fasta2tree.pl --help
	$ {IMAGE} lipm_fastafilter.pl --help
	$ {IMAGE} lipm_fastasplitter.pl --help
	$ {IMAGE} lipm_genome_statistics.pl --help
	$ {IMAGE} lipm_m8_to_gff3.pl --help
	$ {IMAGE} lipm_m8tom8plus.pl --help
	$ {IMAGE} lipm_N50.pl --help
	$ {IMAGE} lipm_nrdb --help
	$ {IMAGE} lipm_smp.pl --help
	$ {IMAGE} lipm_transfer_gff3_attributes.pl --help
	$ {IMAGE} lipm_trim_polyX.pl --help
	$ {IMAGE} lipm_wig_to_expr.pl --help
	$ {IMAGE} merge_gff3_files --help
	$ {IMAGE} relocate_gff3.pl --help
	$ {IMAGE} merge_blastxm8_files --help
	$ {IMAGE} relocate_blastxm8.pl --help
	$ {IMAGE} split_gff3_byseqid.pl --help
	$ {IMAGE} egn_splitbystrand.pl --help

### CITATION

https://lipm-bioinfo.toulouse.inrae.fr
