Bootstrap: docker
From: quay.io/biocontainers/bowtie2:2.4.1--py38he513fc3_0

%labels
    AUTHOR icaoberg
    EMAIL icaoberg@psc.edu
    WEBSITE https://github.com/pscedu/singularity-bowtie2
    COPYRIGHT Copyright © 2021 Pittsburgh Supercomputing Center. All Rights Reserved. 
    VERSION 2.4.1

