Bootstrap: docker
From: vitchyr/railrl_v9_cuda10-1_mj1-50-1-59_torch0-4-1_gym0-10-5_py3-5-2:latest

%post
    mkdir -p /global/scratch
    mkdir -p /global/home/users/vitchyr
    chmod -R 777 /opt
    chmod -R 777 /root
    touch /bin/nvidia-smi
    touch /usr/bin/nvidia-smi
    touch /usr/bin/nvidia-debugdump
    touch /usr/bin/nvidia-persistenced
    touch /usr/bin/nvidia-cuda-mps-control
    touch /usr/bin/nvidia-cuda-mps-server
    mkdir /etc/dcv
    mkdir /var/lib/dcv-gl
    mkdir /usr/lib64
