BootStrap: docker
From: alpine:3.8.4

%labels
  Maintainer Christian Dietrich
  Bowtie2_Version 2.3.5.1

%apprun bowtie2
  exec bowtie2 "${@}"
  
%apprun bowtie2-build
  exec bowtie2-build "${@}"

%apprun bowtie2-inspect  
  exec bowtie2-inspect "${@}"
  
%runscript
  exec bowtie2 "${@}"

%post
  # Get dependencies
  echo "@testing http://mirror.leaseweb.com/alpine/edge/testing" >> /etc/apk/repositories
  apk update
  apk add make g++ zlib-dev zlib perl python libtbb@testing libtbb-dev@testing

  # Install Bowtie2
  wget -q -O - https://github.com/BenLangmead/bowtie2/archive/v2.3.5.1.tar.gz | tar -C /tmp -zxf -
  cd /tmp/bowtie2-*
  make -j$(nproc) install

  # Clean up
  apk del make g++ libtbb-dev zlib-dev
  rm -rf /var/cache/apk/*
