Bootstrap: docker
From: debian:latest

%labels
    MAINTAINER icaoberg
    EMAIL icaoberg@psc.edu
    SUPPORT help@psc.edu
    REPOSITORY http://github.com/pscedu/singularity-aspera-connect
    COPYRIGHT Copyright © 2021 Pittsburgh Supercomputing Center. All Rights Reserved. 
    VERSION 3.11.0.5

%files
    /home/icaoberg/.aspera /opt/aspera

%post
    ln -s /opt/aspera/connect/bin/ascp /usr/bin/ascp
    ln -s /opt/aspera/connect/bin/asperaconnect /usr/bin/asperaconnect
    ln -s /opt/aspera/connect/bin/asperacrypt /usr/bin/asperacrypt
