#!/bin/bash
#
# Boudry Augustin <ogust1@gmail.com>
# 2021: initial version


BootStrap: docker
From: phusion/baseimage:0.11

%labels
  MAINTAINER ogust1@gmail.com

%environment
  export  LC_ALL=en_US.UTF-8
  export  LANGUAGE=en_US.UTF-8
  export  PATH="/miniconda/bin/:${PATH}"
%help


%post
  echo 'debconf debconf/frontend select Noninteractive' | debconf-set-selections
  apt-get clean

  apt-get update
  apt-get -y install build-essential \
  wget



## install miniconda
wget https://repo.continuum.io/miniconda/Miniconda3-4.5.12-Linux-x86_64.sh

bash Miniconda3-4.5.12-Linux-x86_64.sh -p /miniconda -b
rm   Miniconda3-4.5.12-Linux-x86_64.sh

/miniconda/bin/conda config --add channels defaults
/miniconda/bin/conda config --add channels bioconda
/miniconda/bin/conda config --add channels conda-forge


## install starseqr
/miniconda/bin/conda install -c bioconda manta=1.6.0

