Bootstrap: docker
From: alpine:edge

%labels
    MAINTAINER icaoberg
    EMAIL icaoberg@psc.edu
    SUPPORT help@psc.edu
    REPOSITORY https://github.com/pscedu/singularity-asciinema
    COPYRIGHT Copyright © 2021-2025 Pittsburgh Supercomputing Center. All Rights Reserved.
    VERSION 2.4.0
    BASE_IMAGE "alpine:edge"
    DESCRIPTION "Singularity container for running Asciinema, a tool for recording terminal sessions."
    LICENSE "MIT"
    BUILD_DATE "2025-01-03"
    WEBSITE "https://asciinema.org/"

%post
    apk update
    apk add asciinema

%runscript
    asciinema "$@"
