Bootstrap: docker
From: ubuntu:18.04

%setup
mkdir -p ${SINGULARITY_ROOTFS}/src/augment
mkdir -p ${SINGULARITY_ROOTFS}/src/numcodecs
mkdir -p ${SINGULARITY_ROOTFS}/src/zarr
mkdir -p ${SINGULARITY_ROOTFS}/src/gunpowder
mkdir -p ${SINGULARITY_ROOTFS}/src/daisy
mkdir -p ${SINGULARITY_ROOTFS}/src/funlib
mkdir -p ${SINGULARITY_ROOTFS}/src/arid

%files
arid /src/arid/arid
requirements.txt /src/arid/requirements.txt
setup.py /src/arid/setup.py

%labels
maintainer funkej@janelia.hhmi.org

%post

# basic ubuntu packages

apt update
apt install -y --no-install-recommends \
build-essential \
ca-certificates \
cmake \
git \
libmlpack-dev \
liblzma-dev \
wget && \
rm -rf /var/lib/apt/lists/*

# install conda

wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
bash miniconda.sh -b -p /miniconda
PATH="/miniconda/bin:$PATH"
conda config --set always_yes yes --set changeps1 no
conda update -q conda
conda info -a
conda install python=3.6

# install tensorflow

conda install tensorflow-gpu==1.3

# dependencies for arid

AUGMENT_ROOT=/src/augment
AUGMENT_REPOSITORY=https://github.com/funkey/augment.git
AUGMENT_REVISION=4a42b01ccad7607b47a1096e904220729dbcb80a

cd ${AUGMENT_ROOT}
git clone ${AUGMENT_REPOSITORY} . && \
git checkout ${AUGMENT_REVISION}
pip install -r requirements.txt
PYTHONPATH=${AUGMENT_ROOT}:$PYTHONPATH

NUMCODECS_ROOT=/src/numcodecs
NUMCODECS_REPOSITORY=https://github.com/funkey/numcodecs
NUMCODECS_REVISION=f950047d7b666723f81006cbdfd82c0e6705c39c

cd ${NUMCODECS_ROOT}
git clone ${NUMCODECS_REPOSITORY} . && \
git checkout ${NUMCODECS_REVISION} && \
git submodule update --init --recursive
pip install -r requirements.txt
python setup.py install

ZARR_ROOT=/src/zarr
ZARR_REPOSITORY=https://github.com/funkey/zarr
ZARR_REVISION=9ddf849a6e3329f5ff361ebf6156712926e2fdfe

cd ${ZARR_ROOT}
git clone ${ZARR_REPOSITORY} . && \
git checkout ${ZARR_REVISION}
pip install -r requirements.txt
python setup.py install

GUNPOWDER_ROOT=/src/gunpowder
GUNPOWDER_REPOSITORY=https://github.com/funkey/gunpowder.git
GUNPOWDER_REVISION=331caee174e6bf82af909fcaf61adf80ae6bf75e

cd ${GUNPOWDER_ROOT}
git clone ${GUNPOWDER_REPOSITORY} . && \
git checkout ${GUNPOWDER_REVISION}
pip install -r requirements.txt
python setup.py build_ext --inplace
PYTHONPATH=${GUNPOWDER_ROOT}:$PYTHONPATH

DAISY_ROOT=/src/daisy
DAISY_REPOSITORY=https://github.com/funkelab/daisy
DAISY_REVISION=5d0e6c9abbab6a86990d58b3e00ac4332a8ced46

cd ${DAISY_ROOT}
git clone ${DAISY_REPOSITORY} . && \
git checkout ${DAISY_REVISION}
pip install -r requirements.txt
python setup.py build_ext --inplace
PYTHONPATH=${DAISY_ROOT}:$PYTHONPATH

FUNLIB_ROOT=/src/funlib
FUNLIB_REPOSITORY=https://github.com/funkelab/funlib.learn.tensorflow
FUNLIB_REVISION=cbd6e0e78f12cd73e7ce34248e7f06dbf6d22b8b

cd ${FUNLIB_ROOT}
git clone ${FUNLIB_REPOSITORY} . && \
git checkout ${FUNLIB_REVISION}
pip install -r requirements.txt
python setup.py build_ext --inplace
PYTHONPATH=${FUNLIB_ROOT}:$PYTHONPATH

# install arid

# assumes that arid package directory is in build context (the complementary
# Makefile ensures that)
cd /src/arid
python setup.py build_ext --inplace
PYTHONPATH=/src/arid:$PYTHONPATH

%environment
export AUGMENT_ROOT=/src/augment
export PYTHONPATH=${AUGMENT_ROOT}:$PYTHONPATH
export GUNPOWDER_ROOT=/src/gunpowder
export PYTHONPATH=${GUNPOWDER_ROOT}:$PYTHONPATH
export DAISY_ROOT=/src/daisy
export PYTHONPATH=${DAISY_ROOT}:$PYTHONPATH
export FUNLIB_ROOT=/src/funlib
export PYTHONPATH=${FUNLIB_ROOT}:$PYTHONPATH
export PYTHONPATH=/src/lsd:$PYTHONPATH
export PATH=/miniconda/bin:${PATH}

# disable threads for numpy and the like, they get into our way when we
# pre-fetch batches using multiple processes
export OMP_NUM_THREADS=1

%runscript
exec /bin/bash "$@"
