#!/bin/bash
#
# Chadi Saad <chadi.saad@chru-lille.fr>
# 2018/11/06: initial version


BootStrap: docker
From: phusion/baseimage:0.11

%labels
  MAINTAINER chadi.saad@chru-lille.fr

%environment
  export  LC_ALL=en_US.UTF-8
  export  LANGUAGE=en_US.UTF-8
  export  PATH="/miniconda/bin/:${PATH}"

%help


%post
	echo 'debconf debconf/frontend select Noninteractive' | debconf-set-selections
  apt-get clean 

  apt-get update
  apt-get -y install build-essential \
  wget \
  libx11-dev \
  libxext6 \
  libxrender1 \
  texlive \
  pandoc \
  libxml2-dev

export  PATH="/miniconda/bin/:${PATH}"

## install miniconda
wget https://repo.continuum.io/miniconda/Miniconda3-4.5.12-Linux-x86_64.sh 

bash Miniconda3-4.5.12-Linux-x86_64.sh -p /miniconda -b
rm   Miniconda3-4.5.12-Linux-x86_64.sh



conda config --add channels defaults
conda config --add channels bioconda
conda update -n base -c defaults conda

## install R3.5.1
conda install  -c r r-base=3.5.1


## install packages
R -e "install.packages('ggplot2', repos='http://cran.irsn.fr/')"
R -e "install.packages('plotly', repos='http://cran.irsn.fr/')"
R -e "install.packages('rmarkdown', repos='http://cran.irsn.fr/')"
R -e "install.packages('BiocManager',  repos='http://cran.irsn.fr/')"
R -e "BiocManager::install('GenomicFeatures')"
R -e "BiocManager::install('Gviz')"
R -e "BiocManager::install('ggbio')"
