Bootstrap: docker
From: quay.io/biocontainers/bismark:0.22.3--0

%labels
    AUTHOR icaoberg
    EMAIL icaoberg@psc.edu
    WEBSITE http://www.andrew.cmu.edu/~icaoberg
    VERSION 0.22.3

%post
   rm /etc/resolv.conf

####################################################################################
