#!/bin/bash
#
# Christophe Demay <christophe.demay@chru-lille.fr> 
# 2019/02/10: initial version


Bootstrap: docker
From: phusion/baseimage:0.11

%labels
    MAINTAINER christophe.demay@chru-lille.fr
    VERSION 1


%environment
    export  LC_ALL=en_US.UTF-8
    export  LANGUAGE=en_US.UTF-8
    export  PATH=~/bin:$PATH

%help



%post
	echo 'debconf debconf/frontend select Noninteractive' | debconf-set-selections
    apt-get clean 

    apt-get update \
        && apt-get install -y -q \
        git \
        wget \
        curl \
        libz-dev libssl-dev \
        openssl \
        libpng-dev \
        gcc \
        make \
	    zip unzip

    cd /tmp
    git clone https://github.com/ENCODE-DCC/kentUtils.git && \
    cd kentUtils && \
    git checkout  v302.1.0 && \
    make && \
    cp -rp bin/* /usr/local/bin && \
    cd .. && rm -rf kentUtils

	mkdir /.cache && chmod -R 777 /.cache	

    apt-get clean
    apt-get remove --yes --purge build-essential
