#!/bin/bash
#
# Chadi Saad <chadi.saad@chru-lille.fr>
# 2019/09/12: initial version


BootStrap: docker
From: phusion/baseimage:0.11

%labels
  MAINTAINER chadi.saad@chru-lille.fr

%environment
  export  LC_ALL=en_US.UTF-8
  export  LANGUAGE=en_US.UTF-8
  export  getITD_path="/opt/getitd-develop/getitd.py"

%help


%post
  echo 'debconf debconf/frontend select Noninteractive' | debconf-set-selections
  apt-get clean

  apt-get update
  apt-get -y install build-essential \
  python3 \
  python3-pip \
	wget \
	unzip \


pip3 install numpy pandas biopython easygui


mkdir -p /opt
cd /opt
wget https://github.com/tjblaette/getitd/archive/develop.zip -O getITDdevelop.zip

unzip getITDdevelop.zip

