Bootstrap: docker
From: quay.io/biocontainers/bwa:0.7.3a--hed695b0_5

%labels
    AUTHOR icaoberg
    EMAIL icaoberg@psc.edu
    WEBSITE http://gitub.com/pscedu/singularity-bwa
    COPYRIGHT Copyright © 2021 Pittsburgh Supercomputing Center. All Rights Reserved.    
    VERSION 0.7.3a
