Bootstrap: docker
From: debian

%post

    ##### BASE INSTALLATION #####
    apt update
    apt install -y python3 python3-pip vim libssl-dev git curl
    python3 -m pip install --upgrade pip
    python3 -m pip install notebook jupyterhub

    ##### BATCHSPAWNER #####
    latest_batchspawner_release=$(curl --silent "https://api.github.com/repos/jupyterhub/batchspawner/releases/latest" | grep tag_name | sed -E 's/.*"([^"]+)".*/\1/')
    mkdir /opt/batchspawner/
    git clone --depth 1 --branch $latest_batchspawner_release https://github.com/jupyterhub/batchspawner.git /opt/batchspawner/
    pip3 install -e /opt/batchspawner/

    #### JOVYAN USER ####
    useradd -m -s /bin/bash -N -u USER_ID jovyan
    usermod -aG users jovyan

    ##### SET DIRECTORIES TO UID WHO RUNS THE CONTAINER #####
    chown jovyan /opt/
    chown -R jovyan /usr/

%environment
    export NB_USER=jovyan
    export NB_UID=USER_ID
    export NB_GID=100
