Bootstrap: docker
From: rust:1.58.1

%labels
    MAINTAINER icaoberg
    EMAIL icaoberg@psc.edu
    SUPPORT help@psc.edu
    REPOSITORY https://github.com/icaoberg/singularity-rust
    COPYRIGHT Copyright © 2022-2023 Pittsburgh Supercomputing Center. All Rights Reserved.  
    VERSION 1.58.1

%post
