BootStrap: docker
From: ubuntu:bionic

%setup

%files

%environment

%post
    #------------------
    # REQUERIMENTS
    #------------------

    REQUIREMENTS="wget \
                  gcc \
                  openmpi-bin \
                  openmpi-common \
                  openssh-client \
                  libopenmpi-dev"
# \
#                  dapl2-utils \
#                  libdapl-dev \
#                  libdapl2 \
#                  libibverbs1 \
#                  librdmacm1 \
#                  libcxgb3-1 \
#                  libipathverbs1 \
#                  libpmi0 \
#                  libpmi0-dev \
#                  libopenmpi-dev infiniband-diags ibverbs-utils libibverbs-dev \
#                  libcxgb3-1 libipathverbs1 libmlx4-1 libmlx5-1 libmthca1 libnes1
#                  "


    echo "Installing $REQUIREMENTS ..."
    apt-get update
    apt -y --allow-unauthenticated install $REQUIREMENTS

    cd /tmp
    wget https://raw.githubusercontent.com/open-mpi/ompi/master/examples/ring_c.c -O ring_c.c
    mpicc ring_c.c -o /usr/bin/ring

    apt-get clean
    rm -rf /var/lib/apt/lists/*
    rm -rf /var/tmp/*

