BootStrap: docker
From: alpine:latest

%labels
  Maintainer Christian Dietrich
  picard_Version 2.18.17

%apprun picard
  exec java -jar /usr/local/bin/picard.jar "${@}"

%runscript
  exec java -jar /usr/local/bin/picard.jar "${@}"

%post
  # Install OpenJRE 8 (headless)
  echo "http://mirror.leaseweb.com/alpine/v3.8/community" >> /etc/apk/repositories
  apk update
  apk add openjdk8-jre-base
  
  # Install picard
  wget -P /usr/local/bin/ https://github.com/broadinstitute/picard/releases/download/2.18.17/picard.jar  

  # Clean up
  rm -rf /var/cache/apk/*
