#!/bin/bash
#
# Chadi Saad <chadi.saad@chru-lille.fr>
# 2019/03/11: initial version


Bootstrap: docker
From: broadinstitute/gatk:4.1.4.1

%labels
  MAINTAINER chadi.saad@chru-lille.fr
  VERSION 4.1.4.1

%environment

%help

%post