BootStrap: docker
From: continuumio/miniconda3:4.7.12

%apprun kallisto
  exec kallisto "${@}"

%post
  . /opt/conda/bin/activate && \
  conda install -q -y \
    -c bioconda kallisto=0.44.0 && \
  conda clean -a -q -f -y
