Bootstrap: docker
From: alpine:latest

%labels
    MAINTAINER icaoberg
    EMAIL icaoberg@psc.edu
    SUPPORT help@psc.edu
    REPOSITORY https://github.com/icaoberg/singularity-bat
    COPYRIGHT Copyright © 2022 Pittsburgh Supercomputing Center. All Rights Reserved.
    VERSION 0.21.0

%post
    apk update
    apk add bat
