Bootstrap: docker
From: centos:centos6

%setup
mkdir -p $SINGULARITY_ROOTFS/sw/apps
tar -xf resources.tar -C $SINGULARITY_ROOTFS/sw/apps
mkdir -p -m 0700 $SINGULARITY_ROOTFS/root/.ssh/
cp ~/.ssh/config $SINGULARITY_ROOTFS/root/.ssh/
cp ~/.ssh/known_hosts $SINGULARITY_ROOTFS/root/.ssh/
cp ~/.ssh/gitlab_deploy_key $SINGULARITY_ROOTFS/root/.ssh/
chmod 600 $SINGULARITY_ROOTFS/root/.ssh/gitlab_deploy_key
cp ~/.xnat_auth $SINGULARITY_ROOTFS/root/.xnat_auth

%environment
export http_proxy=rcproxy.rc.fas.harvard.edu:3128
export https_proxy=rcproxy.rc.fas.harvard.edu:3128
export no_proxy=ncfcode.rc.fas.harvard.edu,contecentral.rc.fas.harvard.edu,rc.fas.harvard.edu,localhost
export PYTHONPATH=$PYTHONPATH:~/boldqc2
export FREESURFER_HOME=/sw/apps/mri_convert/2015_11_09
export SUBJECTS_DIR=/dev/null
export FSLDIR=/sw/apps/fsl/4.1.7
export FSLOUTPUTTYPE=NIFTI_GZ
export PATH=/sw/apps/miniconda/3.18.3/bin:$PATH
export PATH=$PATH:/sw/apps/mri_convert/2015_11_09/bin
export PATH=$PATH:/sw/apps/fsl/4.1.7/bin
export PATH=$PATH:/sw/apps/xnattools/1.5.4/bin
export PATH=$PATH:/sw/apps/boldqc2/bin

%post
export http_proxy=rcproxy.rc.fas.harvard.edu:3128
export https_proxy=rcproxy.rc.fas.harvard.edu:3128
export no_proxy=ncfcode.rc.fas.harvard.edu
export GIT_SSH_COMMAND='ssh -o StrictHostKeyChecking=no'
yum install -y git tar libgomp which
curl -O https://repo.continuum.io/miniconda/Miniconda2-3.18.3-Linux-x86_64.sh
bash ./Miniconda2-3.18.3-Linux-x86_64.sh -b -f -p /sw/apps/miniconda/3.18.3
export PATH=/sw/apps/miniconda/3.18.3/bin:$PATH
conda install -q -y pil pyyaml lxml
conda install -q -y numpy==1.6.2 
conda install -q -y scipy==0.11.0
conda install -q -y matplotlib==1.2.1
pip install nibabel requests-cache
mkdir /users #for centOS6 compatibility
mkdir -p /sw/apps/boldqc2
cd /sw/apps/boldqc2
git clone --depth 1 git@ncfcode.rc.fas.harvard.edu:nrg/boldqc2.git .
pip install -r requirements.txt
mkdir -m 777 /scratch
mkdir -m 777 /ncf
