#!/bin/bash
#
# Christophe Demay <christophe.demay@chru-lille.fr>
# 2018/04/24: initial version
BootStrap: docker
From: ensemblorg/ensembl-vep:release_92.1
%labels
  MAINTAINER christophe.demay@chru-lille.fr
  VERSION 92.1

%environment

%help

%post


