#!/bin/bash
#
# Christophe Demay <christophe.demay@chru-lille.fr>
# 2021/06/01: initial version


BootStrap: docker
From: waystonesystems/baseimage-centos:latest

%labels
    MAINTAINER christophe.demay@chru-lille.fr

%environment
    export  LC_ALL=en_US.UTF-8
    export  LANGUAGE=en_US.UTF-8

%help

%files
    # from /mnt/isilon_data_nfs/TEAM/PUB/LOGICIELS/ILLUMINA/BCL-Convert/bcl-convert-3.8.2_12_g85770e0b-2.el7.x86_64.rpm 
    bcl-convert-3.8.2_12_g85770e0b-2.el7.x86_64.rpm /tmp

%post

    yum update -y -q && \
    yum install deltarpm gdb -y && \
    rpm -i ${SINGULARITY_CONTAINER}/tmp/bcl-convert-3.8.2_12_g85770e0b-2.el7.x86_64.rpm && \
    yum clean all && \
    rm -rf /var/cache/yum

