Bootstrap: docker
From: quay.io/biocontainers/fastx_toolkit:0.0.14--he1b5a44_8

%labels
    MAINTAINER icaoberg
    EMAIL icaoberg@psc.edu
    SUPPORT help@psc.edu
    REPOSITORY http://gitub.com/pscedu/singularity-fastx-toolkit
    COPYRIGHT Copyright © 2021 Pittsburgh Supercomputing Center. All Rights Reserved.    
    VERSION 0.0.14
