#!/bin/bash
#
# Boudry Augustin <ogust1@gmail.com>
# 2020: initial version


BootStrap: docker
From: phusion/baseimage:0.11

%labels
  MAINTAINER ogust1@gmail.com

%environment
  export  LC_ALL=en_US.UTF-8
  export  LANGUAGE=en_US.UTF-8

%help


%post
  echo 'debconf debconf/frontend select Noninteractive' | debconf-set-selections
  apt-get clean 

  apt-get update
  apt-get -y install build-essential \
  agrep \
  tre-agrep \
  python3 \
  python3-pip \
      wget \


pip3 install numpy pandas biopython 
