Bootstrap: docker
From: ubuntu:22.04

%setup
  mkdir ${SINGULARITY_ROOTFS}/addmc
  cp -t ${SINGULARITY_ROOTFS}/addmc -r ../addmc/libraries ../addmc/src ../addmc/makefile

%post
  export DEBIAN_FRONTEND=noninteractive

  apt update

  apt -y install automake
  apt -y install cmake
  apt -y install g++-11
  apt -y install libgmp-dev

  update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-11 1

  make -C /addmc dmc opt=-Ofast link=-static

%help
  This is a container for the tool DMC.

%runscript
  /addmc/dmc "$@"
