Bootstrap: docker
From: ubuntu:20.04

%setup
  mkdir ${SINGULARITY_ROOTFS}/addmc
  cp -t ${SINGULARITY_ROOTFS}/addmc -r ../addmc/libraries ../addmc/src ../addmc/Makefile

%post
  export DEBIAN_FRONTEND=noninteractive

  apt update

  apt -y install automake
  apt -y install cmake
  apt -y install g++-10
  apt -y install libgmp-dev
  apt -y install libsqlite3-dev
  apt -y install python3-dev

  update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-10 1

  make -C /addmc dmc opt=-Ofast link=-static

%help
  This is a container for the tool DMC.

%runscript
  /addmc/dmc "$@"
