Bootstrap: docker
From: ubuntu:latest

%labels
    MAINTAINER icaoberg
    EMAIL icaoberg@psc.edu
    SUPPORT help@psc.edu
    REPOSITORY https://github.com/pscedu/singularity-cowsay
    COPYRIGHT Copyright © 2022 Pittsburgh Supercomputing Center. All Rights Reserved.
    VERSION 

%environment
    export LC_ALL=C
    export PATH=/usr/games:$PATH

%post
    apt update
    apt install -y cowsay
