Bootstrap: docker
From: perl:5.36.0

%labels
    MAINTAINER icaoberg
    EMAIL icaoberg@psc.edu
    SUPPORT help@psc.edu
    REPOSITORY http://gitub.com/pscedu/singularity-star-fusion
    COPYRIGHT Copyright © 2022 Pittsburgh Supercomputing Center. All Rights Reserved.    
    VERSION 1.11.1

%environment
    export LANGUAGE=en_US.UTF-8
    export LC_ALL=C
    export PERLLIB=$PERLLIB:/opt/STAR-Fusion-v1.11.1/PerlLib
    export PERL5LIB=$PERL5LIB:/opt/STAR-Fusion-v1.11.1/PerlLib

%post
    export DEBIAN_FRONTEND=noninteractive
    apt update && apt-get install -y locales libipc-run3-perl libgd-dev
    locale-gen en_US.UTF-8
    cpan install CPAN::DistnameInfo
    cpan install Pipeliner
    cpan install Tie::Hash
    cpan install DB_File
    cpan install JSON::XS
    #cpan install Math::Round
    #cpan install Font::TTF::Font
    #cpan install Config::General
    #cpan install Clone
    #cpan install GD::Polyline
    #cpan install Math::Bezier
    #cpan install GD
    #cpan install List::MoreUtils
    #cpan install Params::Validate
    #cpan install Readonly
    #cpan install Math::VecStat
    #cpan install Statistics::Basic
    #cpan install Set::IntSpan
    #cpan install Regexp::Common
    #cpan install SVG
    #cpan install Text::Format
    cd /opt
    wget -nc https://github.com/STAR-Fusion/STAR-Fusion/releases/download/STAR-Fusion-v1.11.1/STAR-Fusion-v1.11.1.FULL.tar.gz
    tar -xf STAR-Fusion-v1.11.1.FULL.tar.gz && rm -f STAR-Fusion-v1.11.1.FULL.tar.gz
    ln -s $(pwd)/STAR-Fusion-v1.11.1/STAR-Fusion /usr/local/bin/STAR-Fusion
    ln -s $(pwd)/STAR-Fusion-v1.11.1/FusionInspector/FusionInspector /usr/local/bin/FusionInspector
    ln -s $(pwd)/STAR-Fusion-v1.11.1/FusionFilter/blast_and_promiscuity_filter.pl /usr/local/bin/blast_and_promiscuity_filter.pl
    ln -s $(pwd)/STAR-Fusion-v1.11.1/FusionAnnotator/FusionAnnotator /usr/local/bin/FusionAnnotator
