Bootstrap: docker
From: quay.io/biocontainers/bamtools:2.5.1--he513fc3_6

%labels
    AUTHOR icaoberg
    EMAIL icaoberg@psc.edu
    WEBSITE http://github.com/icaoberg/singularity-bamtools
    COPYRIGHT Copyright © 2021 Pittsburgh Supercomputing Center. All Rights Reserved.
    VERSION 2.5.2

####################################################################################
