Bootstrap: docker
From: quay.io/biocontainers/raxml:8.2.9--h516909a_3

%labels
    AUTHOR icaoberg
    EMAIL icaoberg@psc.edu
    WEBSITE https://gitlab.psc.edu/icaoberg/singularity-raxml
    VERSION 8.2.9
