Bootstrap: docker
From: quay.io/biocontainers/raxml:8.2.9--h516909a_3

%labels
    MAINTAINER  icaoberg
    EMAIL icaoberg@psc.edu
    WEBSITE http://github.com/pscedu/singularity-raxml
    COPYRIGHT Copyright © 2022 Pittsburgh Supercomputing Center. All Rights Reserved. 
    VERSION 8.2.9
