Bootstrap: docker
From: quay.io/biocontainers/fastqc:0.11.9--hdfd78af_1

%labels
    MAINTAINER icaoberg
    EMAIL icaoberg@psc.edu
    SUPPORT help@psc.edu
    REPOSITORY http://gitub.com/pscedu/singularity-fastqc
    COPYRIGHT Copyright © 2023 Pittsburgh Supercomputing Center. All Rights Reserved.    
    VERSION 0.11.9

%environment
    export LC_ALL=C.UTF-8

%post
    locale
