Bootstrap: docker
From: quay.io/biocontainers/fastqc:0.11.9--0

%labels
    MAINTAINER icaoberg
    EMAIL icaoberg@psc.edu
    SUPPORT help@psc.edu
    REPOSITORY http://gitub.com/pscedu/singularity-fastqc
    COPYRIGHT Copyright © 2021 Pittsburgh Supercomputing Center. All Rights Reserved.    
    VERSION 0.11.9
