BootStrap: docker
From: continuumio/miniconda3:4.7.12

%apprun STAR
  exec STAR "${@}"

%post
  . /opt/conda/bin/activate && \
  conda install -q -y \
    -c bioconda star=2.7.3a && \
  conda clean -a -q -f -y
