Bootstrap: docker
From: ubuntu:18.04

%setup
    REPO_ROOT=`dirname $SINGULARITY_BUILDDEF`
    cp -r $REPO_ROOT/ $SINGULARITY_ROOTFS/planner

%post
    ## Install all dependencies.
    apt update
    apt install -y --no-install-recommends cmake g++ make python

    cd /planner
    ./build.py release64

    ## Build h2-mutexes preprocessor.
    mkdir -p builds/h2-mutexes/
    cd builds/h2-mutexes/
    cmake ../../h2-mutexes/
    make -j4

    ## Strip binaries.
    strip --strip-all /planner/builds/release64/bin/downward \
        /planner/builds/h2-mutexes/bin/preprocess

    ## Remove packages unneeded for running the planner.
    apt-get -y autoremove cmake g++ make
    rm -rf /var/lib/apt/lists/*

    ## Only keep essential binaries.
    mkdir -p /compiled-planner/builds/release64
    mv /planner/driver /planner/fast-downward.py /compiled-planner
    mv /planner/builds/release64/bin /compiled-planner/builds/release64
    mv /planner/builds/h2-mutexes/bin/preprocess /compiled-planner
    rm -rf /planner
    mv /compiled-planner /planner

%runscript
    DOMAINFILE=$1
    PROBLEMFILE=$2
    PLANFILE=$3

    ## This version differs from the IPC 2018 version: instead of
    ## diversifying the set of heuristic orders, we use a fixed number
    ## of 10 orders and limit PDB hill climbing by 10 instead of 100
    ## seconds.
    /planner/fast-downward.py \
        --build=release64 \
        --plan-file $PLANFILE \
        --transform-task /planner/preprocess \
        --alias seq-opt-scorpion \
        $DOMAINFILE \
        $PROBLEMFILE
