Bootstrap: docker
From: vitchyr/railrl_v11_cuda10-1_mj2-0-2-2_torch0-3-1_gym0-10-5_py3-5-2:latest

%post
    mkdir -p /global/scratch
    mkdir -p /global/home/users
    export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/root/.mujoco/mujoco200/bin
    export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/root/.mujoco/mujoco150/bin
    chmod -R 777 /opt
    chmod -R 777 /root

%runscript
    exec "$@"
