Bootstrap:docker
From:centos:centos7.8.2003

%labels
MAINTAINER Thomas Green

%environment

%files
hawklogin_rpms.txt /hawklogin_rpms.txt
hawklogin_grouprpms.txt /hawklogin_grouprpms.txt

%runscript
exec /bin/bash /bin/echo "Not supported"

%post
mkdir /scratch
mkdir /software
mkdir /apps
mkdir /app


yum -y install yum-utils

yum -y install wget
yum -y install epel-release

yum -y distribution-synchronization
cat /hawklogin_grouprpms.txt | while read
do
  yum -y groupinstall "$REPLY"
done
yum -y install $(cat /hawklogin_rpms.txt)
rm /hawklogin_grouprpms.txt
rm /hawklogin_rpms.txt

yum -y groupinstall 'MATE Desktop'
yum -y groupinstall 'Compatibility Libraries'
yum -y install https://github.com/openhpc/ohpc/releases/download/v1.3.GA/ohpc-release-1.3-1.el7.x86_64.rpm
yum -y install libXScrnSaver
yum -y install libpng12
yum -y install evince eog
yum -y install glx-utils
yum -y install systemd-libs
yum -y install environment-modules
cd /etc/yum.repos.d
wget https://virtualgl.org/pmwiki/uploads/Downloads/VirtualGL.repo
yum -y install VirtualGL

cat <<EOF > /usr/local/bin/sbatch
#!/bin/bash
MYPROG=\$(basename \$0)
exec ssh -q cl1 "cd \$PWD && \$MYPROG \$@"
EOF

chmod +x /usr/local/bin/sbatch

for SEXEC in squeue sinfo salloc scancel scontrol srun
do
  ln -s sbatch /usr/local/bin/$SEXEC
done

yum install -y python2-pip
pip install ts
yum install -y https://yum.osc.edu/ondemand/1.6/compute/el7Server/x86_64/python-websockify-0.8.0-1.el7.noarch.rpm
yum install -y https://yum.osc.edu/ondemand/latest/compute/el7Server/x86_64/turbovnc-2.2.3-1.el7.x86_64.rpm
yum remove -y tigervnc-server python2-pip mate-power-manager
yum clean all
rm -rf /var/cache/yum/*
