Bootstrap: docker
From: debian:latest

%labels
    MAINTAINER icaoberg
    EMAIL icaoberg@psc.edu
    SUPPORT help@psc.edu
    REPOSITORY http://gitub.com/icaoberg/singularity-fasttree
    COPYRIGHT Copyright © 2021 Pittsburgh Supercomputing Center. All Rights Reserved.   
    VERSION 2.1.11

%post
    apt update
    apt install -y wget libgomp1
    cd /usr/local/bin
    wget http://www.microbesonline.org/fasttree/FastTree
    wget http://www.microbesonline.org/fasttree/FastTreeMP
    wget http://www.microbesonline.org/fasttree/FastTreeDbl
    chmod +x FastTree
    chmod +x FastTreeMP
    chmod +x FastTreeDbl
