#!/bin/bash
#
# Christophe Demay <christophe.demay@chru-lille.fr>


BootStrap: docker
From: phusion/baseimage:0.11

%labels
  MAINTAINER christophe.demay@chru-lille.fr
  VERSION 1.10.1

%environment
  export  LC_ALL=en_US.UTF-8
  export  LANGUAGE=en_US.UTF-8
  export  PATH="/miniconda/bin/:${PATH}"

%help


%post

  echo 'debconf debconf/frontend select Noninteractive' | debconf-set-selections


  apt-get clean 
  apt-get update
  apt-get -y install build-essential \
  python3-setuptools python3-wheel python3-pip \
  wget  \
  git 

python3 -m pip install --upgrade pip
cd /opt
git clone https://github.com/brentp/peddy
cd peddy
python3 -m pip install -r requirements.txt
python3 -m pip install --editable .