Bootstrap: docker
From: alpine:latest

%labels
    AUTHOR icaoberg
    EMAIL icaoberg@psc.edu
    SUPPORT help@psc.edu
    REPOSITORY http://gitub.com/icaoberg/singularity-fdupes
    COPYRIGHT Copyright © 2021 Pittsburgh Supercomputing Center. All Rights Reserved.   
    VERSION 2.1.2

%post
    apk update
    apk add fdupes
