Bootstrap: docker
From: continuumio/miniconda3:4.5.12

%help
A Singularity image for AMR finder plus 

%labels
Maintainer Kristy Horan
Build 1.0
amrfinderplus-3.2.1
db 2019-10-31

%environment
export PATH=/opt/conda/bin:$PATH
%post
# setup the container with appropriate packages - fix issue #17
  apt-get --yes update && apt-get --yes upgrade && apt-get install --yes file && apt-get clean
 # set versions of software to install
  export PATH=/opt/conda/bin:$PATH 
  conda --version
  conda config --add channels conda-forge
  conda config --add channels defaults
  conda config --add channels r
  conda config --add channels bioconda
 
# install amrfinderplus

  conda install -y -c bioconda ncbi-amrfinderplus
  conda update -c bioconda -y ncbi-amrfinderplus
  amrfinder -u 

  
  echo "Done"