Bootstrap: docker
From: debian:latest

%labels
    AUTHOR icaoberg
    EMAIL icaoberg@psc.edu
    SUPPORT help@psc.edu
    REPOSITORY http://gitub.com/pscedu/singularity-lowcharts
    COPYRIGHT Copyright © 2021-2022 Pittsburgh Supercomputing Center. All Rights Reserved.
    VERSION 0.5.8

%post
    apt update
    apt install -y wget
    wget -nc https://github.com/juan-leon/lowcharts/releases/download/v0.5.8/lowcharts_0.5.8_amd64.deb
    dpkg -i lowcharts_0.5.8_amd64.deb && rm -fv lowcharts_0.5.8_amd64.deb
    apt remove -y wget
    apt clean
