Bootstrap:docker
From:nfcore/base:1.9

%labels
	MAINTAINER Björn Hallström <bjorn.hallstrom@skane.se>
	DESCRIPTION Singularity container for CMD microbiology WGS pipeline
	VERSION 0.0.1

%environment
	PATH=/opt/conda/envs/CMD-microwgs/bin/:$PATH
	PICARD_HOME=/opt/conda/envs/CMD-microwgs/share/picard-2.18.26-0/
	PERL5LIB=$PERL5LIB:/opt/conda/envs/CMD-microwgs/lib/site_perl/5.26.2/
	umask 0002

%files
        environment.yml /

%post
        rm -rf /var/lib/apt/lists/*
        apt -y clean
        apt -y update
	apt -y install build-essential make

	/opt/conda/bin/conda env create -f /environment.yml
	/opt/conda/bin/conda clean -a

	/opt/conda/envs/CMD-microwgs/bin/cpanm JSON

