################# Header: Define the base system you want to use ################
# Reference of the kind of base you want to use (e.g., docker, debootstrap, shub).
Bootstrap: docker
# Select the docker image you want to use (Here we choose tensorflow)
From: texlive/texlive:latest-full-doc

# Environment variables that should be sourced at runtime.
%environment
    # use bash as default shell
    SHELL=/bin/bash
    PYTHON_VERSION=3.9
    PATH="/opt/local/bin:${PATH}"
    PYTHONPATH="/opt/llama:/opt/local/bin/:${PYTHONPATH}"
    export SHELL PYTHON_VERSION PATH PYTHONPATH
%files
    requirements.txt requirements.txt
    ./submodules/llama /opt/llama

################# Section: Defining the system #################################
# Commands in the %post section are executed within the container.
%post
    echo "Setting environment variables"
    export DEBIAN_FRONTEND=noninteractive

    echo "Installing Tools with apt-get"
    apt-get update
    apt-get install -y curl \
            wget \
            unzip \
            software-properties-common \
            git \
            entr
    apt-get clean

    # Install apt packages
    apt update
    apt install -y curl software-properties-common build-essential rsync python3-launchpadlib
    add-apt-repository ppa:deadsnakes/ppa -y
    add-apt-repository ppa:rmescandon/yq -y

    # Installing LaTeX packages...
    tlmgr init-usertree && \
    tlmgr update --all
    tlmgr install koma-script

    # Install yq (yaml processing)
    apt install -y yq

    # Set the Python version
    PYTHON_VERSION=3.11
    export PYTHON_VERSION

    echo "Install python${PYTHON_VERSION}.."
    apt install -y python${PYTHON_VERSION}-dev python${PYTHON_VERSION}-distutils python${PYTHON_VERSION}-venv
    python${PYTHON_VERSION} -m venv /opt/local
    update-alternatives --install /usr/bin/python python /opt/local/bin/python${PYTHON_VERSION} 1
    update-alternatives --install /usr/bin/python3 python3 /opt/local/bin/python${PYTHON_VERSION} 1

    echo "Installing pip.."
    curl -sS https://bootstrap.pypa.io/get-pip.py | /opt/local/bin/python3
    update-alternatives --install /usr/local/bin/pip pip /opt/local/bin/pip${PYTHON_VERSION} 1
    update-alternatives --install /usr/local/bin/pip3 pip3 /opt/local/bin/pip${PYTHON_VERSION} 1

    echo "Install basic requirements"
    pip3 install wheel
    pip3 install --upgrade pip

    echo "Installing python requirements"
    pip3 install -r requirements.txt

    echo "Install llama submodule"
    pip3 install -e /opt/llama

    echo "Install NLTK data"
    /opt/local/bin/python3.11 -m nltk.downloader -d /opt/local/share/nltk_data all