Bootstrap: docker
From: debian:jessie-slim

#Includes trimmomatic, fastp, samtools, bwa, bedtools, vcftools, htslib,  kraken2, SNPfinder, freebayes, bbmap

%environment
    export LC_ALL=C

%post
    apt update \
    && apt install -y --no-install-recommends \
    build-essential ca-certificates sudo tcsh\
    git make automake autoconf openjdk-7-jre wget gzip unzip sed\
    zlib1g-dev curl libbz2-dev locales libncurses5-dev liblzma-dev libcurl4-openssl-dev software-properties-common apt-transport-https\
    python3-pip python3-docopt python3-pytest python-dev python3-dev\
    libcurl4-openssl-dev libssl-dev zlib1g-dev fonts-texgyre \
    gcc g++ gfortran libblas-dev liblapack-dev dos2unix libstdc++6\
    r-base-core r-recommended \
    && rm -rf /var/lib/apt/lists/*


    wget -c https://repo.continuum.io/archive/Anaconda3-2020.02-Linux-x86_64.sh
    sh Anaconda3-2020.02-Linux-x86_64.sh -bfp /usr/local

    # add bioconda channels
    conda config --add channels defaults
    conda config --add channels conda-forge
    conda config --add channels bioconda

    # install bulk of bioinformatic tools using conda
    conda create -n AmrPlusPlus_env python=3.9 trimmomatic=0.39 bwa samtools=1.15.1 bedtools kraken=2.1.2 biopython matplotlib=3.5.3 numpy=1.23.1 pysam=0.19.1 pandas=1.4.3 fastqc=0.11.8 multiqc fastp bracken=2.7

    /usr/local/bin/activate AmrPlusPlus_env
    
    #ln -s /usr/local/envs/AmrPlusPlus_env/bin/* /usr/local/bin/
    
    #Still experimenting with how to change $PATH location. 
    echo 'export PATH=$PATH:/usr/local/envs/AmrPlusPlus_env/bin/' >> $SINGULARITY_ENVIRONMENT

    # SNPfinder
    cd /usr/local
    git clone https://github.com/cdeanj/snpfinder.git
    cd snpfinder
    make
    cp snpfinder /usr/local/bin
    cd /

    # Make sure all the tools have the right permissions to use the tools
    chmod -R 777 /usr/local/
    
%test

