Bootstrap: shub
From: tyson-swetnam/turbovnc-singularity

%labels
   AUTHOR argon.argon.argon@gmail.com

%post
    apt-get update -qq
    apt-get install -y fonts-ipafont-nonfree-jisx0208 fonts-ipafont-nonfree-uigothic

