Bootstrap: docker
From: rust:slim-buster

%labels
    MAINTAINER icaoberg
    EMAIL icaoberg@psc.edu
    SUPPORT help@psc.edu
    REPOSITORY https://github.com/icaoberg/singularity-dust
    VERSION 0.6.0

%post
    cargo install du-dust
    ln -s /usr/local/cargo/bin/dust /usr/local/bin/dust

####################################################################################
