Bootstrap: docker
From: anair17/railrl_hand_v2:latest

%post
    mkdir -p /global
    chmod -R 777 /opt
    chmod -R 777 /root
    touch /bin/nvidia-smi
    touch /usr/bin/nvidia-smi
    touch /usr/bin/nvidia-debugdump
    touch /usr/bin/nvidia-persistenced
    touch /usr/bin/nvidia-cuda-mps-control
    touch /usr/bin/nvidia-cuda-mps-server
    mkdir /etc/dcv
    mkdir /var/lib/dcv-gl
    mkdir /usr/lib64
