Bootstrap: docker
From: continuumio/miniconda3

# sudo singularity build pynio.simg Singularity

%environment
  export DEBIAN_FRONTEND=noninteractive
  export PATH=/opt/conda/envs/pynio_env/bin:$PATH 

%post
apt-get update && apt-get install -y build-essential \
                                         git vim

# Updates and Installs
export PATH=/opt/conda/bin:$PATH
/opt/conda/bin/conda create --name pynio_env --channel conda-forge pynio
. activate pynio_env

export PATH=/opt/conda/envs/pynio_env/bin:$PATH
pip install --upgrade pip
