Bootstrap: docker
From: rockylinux:8

%labels
Maintainer eric.burgueno@plantandfood.co.nz
Version 2.40.0

%post
  ## Install official RPM
  yum -y install https://github.com/iterative/dvc/releases/download/2.40.0/dvc-2.40.0-1.x86_64.rpm
  yum clean all
  
%runscript
  exec dvc "$@"
