Bootstrap: docker
From: debian:latest

%labels
    MAINTAINER icaoberg
    EMAIL icaoberg@psc.edu
    MAINTAINER help@psc.edu
    WEBSITE http://www.github.com/icaoberg/singularity-libtiff-tools
    COPYRIGHT Copyright © 2021-2022, Pittsburgh Supercomputing Center. All Rights Reserved. 
    VERSION 4.2.0

%post
    apt-get update
    apt-get install -y libtiff-tools
