BootStrap: docker
From: alpine:latest

%labels
  Maintainer Christian Dietrich
  RepEnrich2_Version 20190521

%apprun RepEnrich2.py
  exec RepEnrich2.py "${@}"

%apprun RepEnrich2_setup.py
  exec RepEnrich2_setup.py "${@}"

%apprun RepEnrich2_subset.py
  exec RepEnrich2_subset.py "${@}"  
  
%runscript
  exec RepEnrich2.py "${@}"  
  
%post
  # Get dependencies
  apk update && apk add make gcc g++ ncurses-dev ncurses-libs zlib-dev zlib bzip2-dev libbz2 xz-dev xz-libs curl-dev libcurl python2 py2-pip python-dev perl libstdc++ libgcc

  # Install SAMtools
  wget -q -O - https://github.com/samtools/samtools/releases/download/1.9/samtools-1.9.tar.bz2 | tar -C /tmp -xjf -
  cd /tmp/samtools-*
  make -j$(nproc) install
  
  # Install bedtools2
  wget -q -O - https://github.com/arq5x/bedtools2/releases/download/v2.28.0/bedtools-2.28.0.tar.gz | tar -C /tmp -zxf -
  cd /tmp/bedtools2
  sed -i 's$/bin/bash$/bin/sh$g' Makefile
  make -j$(nproc) install

  # Install RepEnrich2
  pip install BioPython
  wget -q -O - https://github.com/nerettilab/RepEnrich2/archive/master.zip | busybox unzip -q -d /tmp - 
  mv /tmp/RepEnrich2-*/*.py /usr/local/bin/
  chmod +x /usr/local/bin/*.py
    
  # Clean up
  apk del make gcc g++ python zlib-dev bzip2-dev xz-dev ncurses-dev curl-dev libcurl python-dev
  rm -rf /var/cache/apk/*
