# Singularity definition file for hauntedhouse project, with freesurfer
# Matteo Visconti di Oleggio Castello
# mvdoc.gr@dartmouth.edu
# May 2017

bootstrap: docker
from: neurodebian:jessie

%post
    # install debian packages
    apt-get update
    apt-get install -y eatmydata
    eatmydata apt-get install -y wget bzip2 \
      ca-certificates libglib2.0-0 libxext6 libsm6 libxrender1 \
      git git-annex-standalone
    apt-get clean

    # install anaconda
    if [ ! -d /usr/local/anaconda ]; then
         wget https://repo.continuum.io/archive/Anaconda2-4.3.1-Linux-x86_64.sh \
            -O ~/anaconda.sh && \
         bash ~/anaconda.sh -b -p /usr/local/anaconda && \
         rm ~/anaconda.sh
    fi
    # set anaconda path
    export PATH="/usr/local/anaconda/bin:$PATH"

    # install specific versions of packages for reproducibility
    conda install\
        pip=9.0.1 \
        numpy=1.11.3 scipy=0.18.1 scikit-learn=0.18.1 scikit-image=0.12.3 \
        pandas=0.19.2 seaborn=0.7.1 jupyter ipython=5.3.0 joblib=0.9.4 \
        pyqt=4
    conda clean --tarballs
    pip install mne==0.13 duecredit

    # install freesurfer
    wget -qO- https://surfer.nmr.mgh.harvard.edu/pub/dist/freesurfer/6.0.0/freesurfer-Linux-centos6_x86_64-stable-pub-v6.0.0.tar.gz | tar zxv -C /opt

    # make /data and /scripts so we can mount it to access external resources
    if [ ! -d /data ]; then mkdir /data; fi
    if [ ! -d /scripts ]; then mkdir /scripts; fi

    # add license key for freesurfer
    echo "cHJpbnRmICJrcnp5c3p0b2YuZ29yZ29sZXdza2lAZ21haWwuY29tXG41MTcyXG4gKkN2dW12RVYzelRmZ1xuRlM1Si8yYzFhZ2c0RVxuIiA+IC9vcHQvZnJlZXN1cmZlci9saWNlbnNlLnR4dAo=" | base64 -d | sh

%environment
    # copied from dockerfile bidsapps/freesurfer
    OS="Linux"
    FS_OVERRIDE=0
    FIX_VERTEX_AREA=""
    FREESURFER_HOME="/opt/freesurfer"
    SUBJECTS_DIR="/opt/freesurfer/subjects"
    FSF_OUTPUT_FORMAT="nii.gz"
    MNI_DIR="/opt/freesurfer/mni"
    LOCAL_DIR="/opt/freesurfer/local"
    FREESURFER_HOME="/opt/freesurfer"
    FSFAST_HOME="/opt/freesurfer/fsfast"
    MINC_BIN_DIR="/opt/freesurfer/mni/bin"
    MINC_LIB_DIR="/opt/freesurfer/mni/lib"
    MNI_DATAPATH="/opt/freesurfer/mni/data"
    FMRI_ANALYSIS_DIR="/opt/freesurfer/fsfast"
    PERL5LIB="/opt/freesurfer/mni/lib/perl5/5.8.5"
    MNI_PERL5LIB="/opt/freesurfer/mni/lib/perl5/5.8.5"

    PATH="/opt/freesurfer/bin:/opt/freesurfer/fsfast/bin:/opt/freesurfer/tktools:/opt/freesurfer/mni/bin:/usr/local/anaconda/bin:$PATH"

%runscript
    exec /bin/bash
