BootStrap: docker
From: continuumio/miniconda:latest
IncludeCmd: yes

%help

%setup
	#chmod 755 /lab/work/porchard/sn-muscle-project/singularity/doubletfinder/doubletfinder.simg

%files

%labels

%environment

%post
	umask 0022
	apt update
	apt -y dist-upgrade
	apt -y install build-essential git environment-modules wget libxml2-dev libssl-dev tar gzip libgsl-dev
	apt install -y libboost-all-dev libhts-dev libncurses5-dev libtinfo-dev zlib1g-dev lcov
	export PATH=/opt/conda/bin:$PATH
	conda install -c conda-forge -c bioconda -c defaults r-devtools r-optparse r-tidyverse r-seurat=3.0.2
	mkdir -p /sw
	mkdir -p /scratch
	mkdir -p /gpfs
	ln -s /bin/gzip /usr/bin/gzip
	ln -s /bin/tar /bin/gtar
	Rscript -e "library(devtools); devtools::install_github('chris-mcginnis-ucsf/DoubletFinder')"
