Bootstrap: docker
From: quay.io/biocontainers/gatk4:4.2.0.0--hdfd78af_1

%labels
    AUTHOR icaoberg
    EMAIL icaoberg@psc.edu
    WEBSITE https://github.com/pscedu/singularity-gatk
    COPYRIGHT Copyright © 2021 Pittsburgh Supercomputing Center. All Rights Reserved.
    VERSION 4.2.0.0
