Bootstrap: docker
From: continuumio/miniconda3

%labels
   MAINTAINER Arun Seetharam
   EMAIL arnstrm@iastate.edu

%test
    python3 --version

%files
    env.yml
%environment
    export PATH=/opt/conda/envs/nucleoatac/bin/:$PATH
    export PATH=/opt/nucleoatac:/opt/nucleoatac/src:/opt/nucleoatac/src/utils:$PATH

%post

    apt update
    apt install -y software-properties-common
    DEBIAN_FRONTEND=noninteractive
    apt update
    apt install -y build-essential wget curl git autoconf automake
    apt install -y gcc g++ bison make cmake
    apt install -y perl zlib1g-dev libbz2-dev liblzma-dev libcurl4-gnutls-dev libssl-dev libtool libncurses5-dev liblpsolve55-dev rsync librsync-dev
    apt install -y libboost-dev '^libboost-.*71-dev'
    apt install -y python3 python3-numpy python3-dev python3-scipy python3-pandas python3-pip
    apt install -y perl
    /opt/conda/bin/conda env create -f env.yml
    . "/opt/conda/etc/profile.d/conda.sh"
    conda activate nucleoatac
    # Agora
    cd /opt
    git clone https://github.com/GreenleafLab/NucleoATAC.git
    cd NucleoATAC/
    pip install .

%runscript
    exec /opt/conda/envs/nucleoatac/bin/"$@"
    
