#!/bin/bash
#
# Chadi Saad <chadi.saad@chru-lille.fr>
# 2019/02/01: initial version


BootStrap: docker
From: phusion/baseimage:0.11

%labels
  MAINTAINER chadi.saad@chru-lille.fr

%help
    UMITOOLS 1.0.0

%environment
    export LC_ALL=C
    export PATH=/miniconda/envs/umi_tools_env/bin:$PATH


%post
	echo 'debconf debconf/frontend select Noninteractive' | debconf-set-selections

  apt-get update
  apt-get -y install build-essential \
  wget \
  unzip \
  gcc \
  zlib1g-dev 


  wget https://repo.continuum.io/miniconda/Miniconda2-4.7.12.1-Linux-x86_64.sh 

  bash Miniconda2-4.7.12.1-Linux-x86_64.sh -p /miniconda -b
  rm   Miniconda2-4.7.12.1-Linux-x86_64.sh
  export  PATH="/miniconda/bin/:${PATH}"

  conda config --add channels defaults
  conda config --add channels bioconda
  conda config --add channels conda-forge
  conda config --set ssl_verify no
  conda config --set default_threads 12


  conda update -y conda
  conda create -n umi_tools_env -c bioconda python=3.7 umi_tools 
  conda init bash
  exec bash -l
  conda activate umi_tools_env






