Bootstrap: docker
From: quay.io/biocontainers/spades:3.14.1--h2d02072_0

%labels
    AUTHOR icaoberg
    EMAIL icaoberg@psc.edu
    WEBSITE https://gitlab.psc.edu/icaoberg/singularity-spades
    VERSION 3.14.1

%post
   rm /etc/resolv.conf

####################################################################################
