Bootstrap: docker
From: debian:latest

%labels
    AUTHOR icaoberg
    MAINTAINER icaoberg@psc.edu
    WEBSITE https://github.com/icaoberg/singularity-shellcheck
    VERSION 0.5.0

%post
    apt update
    apt install -y shellcheck

####################################################################################
