BootStrap: docker
From: jupyter/r-notebook:r-4.1.0

# Dependencies
%post
  chmod -R o+w /etc/profile && \
  echo "export R_HOME=/opt/conda/lib/R" >> /etc/profile && \
  . /etc/profile && \
  echo "options(repos = c(CRAN = 'https://cran.rstudio.com/'), download.file.method = 'libcurl')" >> ${R_HOME}/etc/Rprofile.site && \
  chmod -R o-w /etc/profile && \
  apt update --allow-insecure-repositories && \
  apt -y install ghostscript \
                 libcairo2-dev \
                 g++

# R basis
%post
  R -e 'install.packages("tidyverse")' && \
  R -e 'install.packages("furrr")' && \
  R -e 'install.packages("here")' && \
  R -e 'install.packages("docopt")' && \
  R -e 'install.packages("ggpubr")' && \
  R -e 'install.packages("ggplotify")' && \
  R -e 'install.packages("ggrepel")' && \
  R -e 'install.packages("ggedit")' && \
  R -e 'install.packages("ggcorrplot")' && \
  R -e 'install.packages("plotly")' && \
  R -e 'install.packages("formatR", repos = "http://cran.rstudio.com")' && \
  R -e 'install.packages("XML")'

# cgrtextbook
%post
  conda install -q -y -c bioconda r-enrichr \
    bioconductor-complexheatmap && \
  conda clean -a -q -f -y && \
  R -e 'BiocManager::install(c("qvalue", "plot3D", "pheatmap", "cowplot", "cluster", "NbClust", "fastICA", "NMF", "matrixStats", "Rtsne", "mosaic", "knitr", "genomation", "ggbio", "Gviz", "DESeq2", "RUVSeq", "gProfileR", "ggfortify", "corrplot", "gage", "EDASeq", "citr", "svglite", "Rqc", "ShortRead", "QuasR", "methylKit", "FactoMineR", "iClusterPlus", "caret", "xgboost", "glmnet", "DALEX", "kernlab", "pROC", "nnet", "RANN", "ranger", "GenomeInfoDb", "GenomicRanges", "GenomicAlignments", "circlize", "rtracklayer", "BSgenome.Hsapiens.UCSC.hg38", "BSgenome.Hsapiens.UCSC.hg19", "AnnotationHub", "GenomicFeatures", "normr", "MotifDb", "TFBSTools", "rGADEM", "JASPAR2018"), force = TRUE)' && \
  R -e 'install.packages("devtools")' && \
  R -e 'devtools::install_github("compgenomr/compGenomRData")'

# Jupyter extensions
%post
  apt -y install nodejs \
                 npm && \
  conda install -c conda-forge jupyter_contrib_nbextensions

# Set .libPaths
%post
  . /etc/profile && \
  echo "export R_LIBS_SITE=${HOME}/R/x86_64-conda-linux-gnu-library/4.1:$R_LIBS_SITE" >> ${R_HOME}/etc/Renviron.site && \
  echo 'export R_LIBS=${HOME}/R/x86_64-conda-linux-gnu-library/4.1:$R_LIBS' >> ${R_HOME}/etc/Renviron
