Bootstrap: docker

From: continuumio/miniconda3

%files
    conda-lock.yml

%post
    /opt/conda/bin/conda install -c conda-forge conda-lock
    /opt/conda/bin/conda-lock install -n treeshrinkenv conda-lock.yml

%runscript
    exec /opt/conda/envs/treeshrinkenv/bin/run_treeshrink.py "$@"

