Bootstrap: docker
From: ghcr.io/plasmafair/epoch:v0.3.1

%help

    This is a Singularity container for running Epoch. It provides an
    interface to 1D, 2D and 3D Epoch executables, plus variations with
    different compiler flags switched on.

    Before running Epoch via this container, first load the Singularity and
    OpenMPI modules:

      $ module load tools/Singularity mpi/OpenMPI

    It can then be run using:

      $ mpirun -n <nprocs> singularity exec <img> \
          run_epoch -d <dims> -o <outdir>

    The parts in <angle brackets> must be filled in by you:

      - <nprocs>: The number of MPI processes to run on. This should be
        set to "${SLURM_NTASKS}" in most cases.
      - <img>: The Singularity image file, or the URI of an uploaded
        image.
      - <dims>: The number of dimensions to run with. If not provided,
        the default is 1.
      - <outdir>: The directory to write results to. If we want to write
        to the current directory, this can just be '.'. Your "input.deck"
        files should be located here. This must be provided, as it
        defaults to '/output' due to the requirements of the base Docker
        image.

    You can also provide the flag '--photons' to include QED effects.

    To look around inside the container, try:

      $ singularity run <img>

    The Epoch repository can be located in the /app/epoch directory.

    An example sbatch script might look like:

      #!/bin/bash
      #SBATCH --job-name=singularity_epoch  # Job name
      #SBATCH --mail-type=END,FAIL          # Mail events (NONE, BEGIN, END, FAIL, ALL)
      #SBATCH --mail-user=usr501@york.ac.uk # Where to send mail
      #SBATCH --ntasks=2                    # Run n tasks...
      #SBATCH --cpus-per-task=1             # ...with one core each
      #SBATCH --mem-per-cpu=1gb             # Memory per processor
      #SBATCH --time=00:05:00               # Time limit hrs:min:sec
      #SBATCH --output=epoch_%j.log         # Standard output and error log
      #SBATCH --account=my_proj_account     # Project account
         
      module purge
      module load mpi/OpenMPI tools/Singularity
      mpirun -n ${SLURM_NTASKS} singularity exec epoch.sif run_epoch -d 2 -o .

    Make sure you have your deck in the output directory with the name "input.deck"

%post

    # Docker runs as root, but Singularity runs as user.
    # Need to add user permissions to working folder
    chmod --recursive 755 /app/epoch/bin

%runscript

    # When using 'singularity run', opens interactive shell
    # To run epoch, always use 'singularity exec' instead!
    /bin/bash
