Bootstrap: docker
From: gnuoctave/octave:6.2.0

%labels
    MAINTAINER icaoberg
    EMAIL icaoberg@psc.edu
    SUPPORT help@psc.edu
    WEBSITE http://github.com/pscedu/singularity-octave
    COPYRIGHT Copyright © 2021, Pittsburgh Supercomputing Center. All Rights Reserved. 
    VERSION 6.2.0

%environment
    export DISPLAY=hostname:0.0

%post
    apt-get update
    apt-get install -y gnuplot pandoc

    octave --eval "pkg install https://octave.sourceforge.io/download.php?package=general-2.1.1.tar.gz"
    octave --eval "pkg install https://octave.sourceforge.io/download.php?package=image-2.12.0.tar.gz"
    octave --eval "pkg install https://octave.sourceforge.io/download.php?package=io-2.6.3.tar.gz"
    octave --eval "pkg install https://octave.sourceforge.io/download.php?package=control-3.3.1.tar.gz"
    octave --eval "pkg install https://octave.sourceforge.io/download.php?package=signal-1.4.1.tar.gz"
    octave --eval "pkg install https://octave.sourceforge.io/download.php?package=struct-1.0.17.tar.gz"
    octave --eval "pkg install https://octave.sourceforge.io/download.php?package=parallel-4.0.1.tar.gz"
    octave --eval "pkg install https://octave.sourceforge.io/download.php?package=splines-1.3.4.tar.gz"
