Bootstrap: docker
From: rust:slim-buster

%labels
    AUTHOR icaoberg
    MAINTAINER icaoberg@psc.edu
    SUPPORT help@psc.edu
    REPOSITORY https://github.com/icaoberg/singularity-dust
    VERSION 0.5.4

%post
    cargo install du-dust
    ln -s /usr/local/cargo/bin/dust /usr/local/bin/dust

####################################################################################
