#!/bin/bash
#
# Chadi Saad <chadi.saad@chru-lille.fr>
# 2018/11/06: initial version


BootStrap: docker
From: r-base:3.1.3

%labels
  MAINTAINER chadi.saad@chru-lille.fr

%environment
  export  LC_ALL=en_US.UTF-8
  export  LANGUAGE=en_US.UTF-8
  export  PATH="/opt/DECoN-1.0.2/Linux/:${PATH}"

%help

%post

	echo 'debconf debconf/frontend select Noninteractive' | debconf-set-selections
  apt-get clean

  apt-get update
  apt-get -y install build-essential gfortran gcc wget 
  
  R -e "install.packages('packrat', repos='http://cran.irsn.fr/')"
  R -e "install.packages('R.utils', repos='http://cran.irsn.fr/')"
  R -e "install.packages('labeling', repos='http://cran.irsn.fr/')"
  R -e "install.packages('shiny', repos='http://cran.irsn.fr/')"



  cd /opt

  wget --no-check-certificate -O DECoN-1.0.2.tar.gz  https://github.com/RahmanTeam/DECoN/archive/v1.0.2.tar.gz
  
  tar xvzf DECoN-1.0.2.tar.gz
  rm DECoN-1.0.2.tar.gz
  


  cd /opt/DECoN-1.0.2/Linux

  bash setup.sh

  echo "symlink.system.packages: TRUE" >> packrat/packrat.opts

  chmod +x /opt/DECoN-1.0.2/Linux/*.R