#!/bin/bash
#

BootStrap: docker
From: phusion/baseimage:0.11


%environment
  export  LC_ALL=en_US.UTF-8
  export  LANGUAGE=en_US.UTF-8
%help


%post
  echo 'debconf debconf/frontend select Noninteractive' | debconf-set-selections
  apt-get clean 

  apt-get update
  apt-get -y install build-essential \
  postgresql-client  