Bootstrap: docker
From: ubuntu:latest

%setup
      #Runs on host. The path to the image is $SINGULARITY_ROOTFS

%post
      #Post setup, runs inside the image

      #Default mount paths
          mkdir /scratch /data /shared /fastdata

      #Install the packages you
          apt-get update
	        apt-get install -y wget git vim cmake
          apt-get install -y libboost-all-dev doxygen
          apt-get install -y qt5-default
          apt-get install -y build-essential
          apt-get install -y libfontconfig1
          apt-get install -y mesa-common-dev
          apt-get install -y libsdl2-dev libsdl2-2.0

          apt-get install -y autoconf automake libtool libgoogle-glog-dev libgflags-dev libeigen3-dev libconfig-dev libconfig++-dev
          git clone https://github.com/beniz/libcmaes.git
          cd libcmaes
          echo "#define CMAES_EXPORT" > cmaes_export.h
          ./autogen.sh
          ./configure --prefix=/usr/local
          make
          make install
          make check

          cd /usr/local/include/libcmaes
          echo "#define CMAES_EXPORT" > cmaes_export.h

          ldconfig



%runscript
      #Runs inside the image every time it starts up

%test
      #Test script to verify that the image is built and running correctly
