Bootstrap: docker
From: continuumio/miniconda3

%help
	Container with Brian Haas' TransDecoder, which identifies candidate coding regions within transcript sequences, such as those generated by de novo RNA-Seq transcript assembly using Trinity, or constructed based on RNA-Seq alignments to the genome using Tophat and Cufflinks.
	This installation is based on bioconda transdecoder 5.5.0

%labels
        author Stefano Ghignone
        maintainer sghignone
        name TransDecoder
        version 5.5.0

%post
        #SET CONDA ENVIRONMENT
        export PATH=/opt/conda/bin:${PATH}
	conda update -y conda
        conda update -n base -c defaults conda
        conda config --add channels conda-forge && \
        conda config --add channels bioconda && \
        conda config --add channels default
        #INSTALL SOFTWARE
        conda install -c bioconda transdecoder  && conda clean -a
