Bootstrap: docker
From: quay.io/fenicsproject/stable:current


%files
    WELCOME.Singularity /usr/local/share/WELCOME

%post
    chmod a+r /usr/local/share/WELCOME
    ldconfig

%runscript
    cat /usr/local/share/WELCOME 
    exec /bin/bash -i
