Bootstrap: docker
From: alpine:edge

%labels
    AUTHOR icaoberg
    MAINTAINER icaoberg@psc.edu
    WEBSITE http://www.andrew.cmu.edu/~icaoberg

%post
    apk update
    apk add git wget
    wget -nc https://github.com/jesseduffield/lazygit/releases/download/v0.23.1/lazygit_0.23.1_Linux_x86_64.tar.gz
    tar -xvf lazygit_0.23.1_Linux_x86_64.tar.gz
    mv lazygit /usr/local/bin
    rm -f README.md LICENSE lazygit_0.23.1_Linux_x86_64.tar.gz
