Bootstrap: docker
From: rust:slim-buster

%labels
    MAINTAINER icaoberg
    EMAIL icaoberg@psc.edu
    SUPPORT help@psc.edu
    COPYRIGHT Copyright © 2021-2023 Pittsburgh Supercomputing Center. All Rights Reserved.
    REPOSITORY https://github.com/icaoberg/singularity-dust
    VERSION 0.8.4

%post
    cargo install --version 0.8.4 du-dust
    ln -s /usr/local/cargo/bin/dust /usr/local/bin/dust
